/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ENGINE_H
#define ENGINE_H


INLINE_ENGINE\
(void)
engine_v850_run (SIM_DESC sd,
                 int next_cpu_nr,
                 int nr_cpus,
                 int siggnal);

INLINE_ENGINE\
(void)
engine_v850e_run (SIM_DESC sd,
                  int next_cpu_nr,
                  int nr_cpus,
                  int siggnal);

INLINE_ENGINE\
(void)
engine_v850e1_run (SIM_DESC sd,
                   int next_cpu_nr,
                   int nr_cpus,
                   int siggnal);

INLINE_ENGINE\
(void)
engine_v850e2_run (SIM_DESC sd,
                   int next_cpu_nr,
                   int nr_cpus,
                   int siggnal);

INLINE_ENGINE\
(void)
engine_v850e2v3_run (SIM_DESC sd,
                     int next_cpu_nr,
                     int nr_cpus,
                     int siggnal);

INLINE_ENGINE\
(void)
engine_v850e3v5_run (SIM_DESC sd,
                     int next_cpu_nr,
                     int nr_cpus,
                     int siggnal);

#endif /* _ENGINE_H_*/
