/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef IRUN_C
#define IRUN_C

#include "sim-main.h"
#include "engine.h"
#include "idecode.h"
#include "bfd.h"


instruction_address (*idecode_issue)
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);


void (*engine_run)
(SIM_DESC sd,
 int next_cpu_nr,
 int nr_cpus,
 int siggnal);

void
sim_engine_run (SIM_DESC sd,
                int next_cpu_nr,
                int nr_cpus,
                int siggnal)
{
  int mach;
  if (STATE_ARCHITECTURE (sd) == NULL)
    mach = 0;
  else
    mach = STATE_ARCHITECTURE (sd)->mach;
  switch (mach)
    {
    case bfd_mach_v850:
      idecode_issue = idecode_v850_issue;
      engine_run = engine_v850_run;
      break;
    case bfd_mach_v850e:
      idecode_issue = idecode_v850e_issue;
      engine_run = engine_v850e_run;
      break;
    case bfd_mach_v850e1:
      idecode_issue = idecode_v850e1_issue;
      engine_run = engine_v850e1_run;
      break;
    case bfd_mach_v850e2:
      idecode_issue = idecode_v850e2_issue;
      engine_run = engine_v850e2_run;
      break;
    case bfd_mach_v850e2v3:
      idecode_issue = idecode_v850e2v3_issue;
      engine_run = engine_v850e2v3_run;
      break;
    case bfd_mach_v850e3v5:
      idecode_issue = idecode_v850e3v5_issue;
      engine_run = engine_v850e3v5_run;
      break;
    default:
      sim_engine_abort (sd, NULL, NULL_CIA,
                        "sim_engine_run - unknown machine");
      break;
    }
  engine_run (sd, next_cpu_nr, nr_cpus, siggnal);
}

#endif /* _IRUN_C_*/
