/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 90 "./v850/v850.igen"
  itable_add_I,
#line 96 "./v850/v850.igen"
  itable_add_II,
#line 105 "./v850/v850.igen"
  itable_addi_VI,
#line 114 "./v850/v850.igen"
  itable_adf_XI,
#line 129 "./v850/v850.igen"
  itable_and_I,
#line 138 "./v850/v850.igen"
  itable_andi_VI,
#line 183 "./v850/v850.igen"
  itable_Bcond_III,
#line 198 "./v850/v850.igen"
  itable_Bcond_VII,
#line 215 "./v850/v850.igen"
  itable_bsh_XII,
#line 243 "./v850/v850.igen"
  itable_bsw_XII,
#line 274 "./v850/v850.igen"
  itable_callt_II,
#line 295 "./v850/v850.igen"
  itable_caxi_IX,
#line 344 "./v850/v850.igen"
  itable_clr1_VIII,
#line 350 "./v850/v850.igen"
  itable_clr1_IX,
#line 364 "./v850/v850.igen"
  itable_ctret_X,
#line 380 "./v850/v850.igen"
  itable_cmov_XI,
#line 394 "./v850/v850.igen"
  itable_cmov_XII,
#line 411 "./v850/v850.igen"
  itable_cmp_I,
#line 417 "./v850/v850.igen"
  itable_cmp_II,
#line 426 "./v850/v850.igen"
  itable_di_X,
#line 437 "./v850/v850.igen"
  itable_dispose_XIII,
#line 473 "./v850/v850.igen"
  itable_div_XI,
#line 486 "./v850/v850.igen"
  itable_divh_I,
#line 533 "./v850/v850.igen"
  itable_divh_XI,
#line 546 "./v850/v850.igen"
  itable_divhu_XI,
#line 559 "./v850/v850.igen"
  itable_divu_XI,
#line 572 "./v850/v850.igen"
  itable_divq_XI,
#line 596 "./v850/v850.igen"
  itable_divqu_XI,
#line 620 "./v850/v850.igen"
  itable_ei_X,
#line 629 "./v850/v850.igen"
  itable_eiret_X,
#line 655 "./v850/v850.igen"
  itable_feret_X,
#line 680 "./v850/v850.igen"
  itable_fetrap_I,
#line 702 "./v850/v850.igen"
  itable_halt_X,
#line 711 "./v850/v850.igen"
  itable_hsh_XII,
#line 733 "./v850/v850.igen"
  itable_hsw_XII,
#line 762 "./v850/v850.igen"
  itable_jarl_V,
#line 770 "./v850/v850.igen"
  itable_jarl32_VI,
#line 783 "./v850/v850.igen"
  itable_jarl_reg_XI,
#line 794 "./v850/v850.igen"
  itable_jmp_I,
#line 801 "./v850/v850.igen"
  itable_jmp32_VI,
#line 814 "./v850/v850.igen"
  itable_jr_V,
#line 823 "./v850/v850.igen"
  itable_jr32_VI,
#line 836 "./v850/v850.igen"
  itable_ld_b_VII,
#line 842 "./v850/v850.igen"
  itable_ld_b_XIV,
#line 853 "./v850/v850.igen"
  itable_ld_h_VII,
#line 859 "./v850/v850.igen"
  itable_ld_h_XIV,
#line 870 "./v850/v850.igen"
  itable_ld_w_VII,
#line 876 "./v850/v850.igen"
  itable_ld_w_XIV,
#line 887 "./v850/v850.igen"
  itable_ld_dw_XIV,
#line 900 "./v850/v850.igen"
  itable_ld_bu_VII,
#line 911 "./v850/v850.igen"
  itable_ld_bu_XIV,
#line 922 "./v850/v850.igen"
  itable_ld_hu_VII,
#line 933 "./v850/v850.igen"
  itable_ld_hu_XIV,
#line 947 "./v850/v850.igen"
  itable_ldsr_IX,
#line 1110 "./v850/v850.igen"
  itable_mac_XI,
#line 1184 "./v850/v850.igen"
  itable_macu_XI,
#line 1236 "./v850/v850.igen"
  itable_mov_I,
#line 1244 "./v850/v850.igen"
  itable_mov_II,
#line 1250 "./v850/v850.igen"
  itable_mov_VI,
#line 1267 "./v850/v850.igen"
  itable_movea_VI,
#line 1278 "./v850/v850.igen"
  itable_movhi_VI,
#line 1287 "./v850/v850.igen"
  itable_mul_XI,
#line 1298 "./v850/v850.igen"
  itable_mul_XII,
#line 1311 "./v850/v850.igen"
  itable_mulh_I,
#line 1317 "./v850/v850.igen"
  itable_mulh_II,
#line 1326 "./v850/v850.igen"
  itable_mulhi_VI,
#line 1335 "./v850/v850.igen"
  itable_mulu_XI,
#line 1346 "./v850/v850.igen"
  itable_mulu_XII,
#line 1360 "./v850/v850.igen"
  itable_nop_I,
#line 1369 "./v850/v850.igen"
  itable_not_I,
#line 1378 "./v850/v850.igen"
  itable_not1_VIII,
#line 1384 "./v850/v850.igen"
  itable_not1_IX,
#line 1398 "./v850/v850.igen"
  itable_or_I,
#line 1407 "./v850/v850.igen"
  itable_ori_VI,
#line 1416 "./v850/v850.igen"
  itable_prepare_XIII,
#line 1444 "./v850/v850.igen"
  itable_prepare00_XIII,
#line 1455 "./v850/v850.igen"
  itable_prepare01_XIII,
#line 1466 "./v850/v850.igen"
  itable_prepare10_XIII,
#line 1477 "./v850/v850.igen"
  itable_prepare11_XIII,
#line 1489 "./v850/v850.igen"
  itable_reti_X,
#line 1513 "./v850/v850.igen"
  itable_sar_IX,
#line 1519 "./v850/v850.igen"
  itable_sar_II,
#line 1525 "./v850/v850.igen"
  itable_sar_XI,
#line 1538 "./v850/v850.igen"
  itable_sasf_IX,
#line 1552 "./v850/v850.igen"
  itable_satadd_I,
#line 1558 "./v850/v850.igen"
  itable_satadd_II,
#line 1564 "./v850/v850.igen"
  itable_satadd_XI,
#line 1578 "./v850/v850.igen"
  itable_satsub_I,
#line 1584 "./v850/v850.igen"
  itable_satsub_XI,
#line 1598 "./v850/v850.igen"
  itable_satsubi_VI,
#line 1607 "./v850/v850.igen"
  itable_satsubr_I,
#line 1616 "./v850/v850.igen"
  itable_sbf_XI,
#line 1631 "./v850/v850.igen"
  itable_sch0l_IX,
#line 1681 "./v850/v850.igen"
  itable_sch0r_IX,
#line 1729 "./v850/v850.igen"
  itable_sch1l_IX,
#line 1777 "./v850/v850.igen"
  itable_sch1r_IX,
#line 1825 "./v850/v850.igen"
  itable_shl_XI,
#line 1837 "./v850/v850.igen"
  itable_shr_XI,
#line 1851 "./v850/v850.igen"
  itable_setf_IX,
#line 1860 "./v850/v850.igen"
  itable_set1_VIII,
#line 1866 "./v850/v850.igen"
  itable_set1_IX,
#line 1880 "./v850/v850.igen"
  itable_shl_IX,
#line 1886 "./v850/v850.igen"
  itable_shl_II,
#line 1895 "./v850/v850.igen"
  itable_shr_IX,
#line 1901 "./v850/v850.igen"
  itable_shr_II,
#line 1910 "./v850/v850.igen"
  itable_sld_b_IV,
#line 1929 "./v850/v850.igen"
  itable_sld_h_IV,
#line 1948 "./v850/v850.igen"
  itable_sld_w_IV,
#line 1957 "./v850/v850.igen"
  itable_sld_bu_IV,
#line 1981 "./v850/v850.igen"
  itable_sld_hu_IV,
#line 2008 "./v850/v850.igen"
  itable_sst_b_IV,
#line 2014 "./v850/v850.igen"
  itable_sst_h_IV,
#line 2020 "./v850/v850.igen"
  itable_sst_w_IV,
#line 2027 "./v850/v850.igen"
  itable_st_b_VII,
#line 2033 "./v850/v850.igen"
  itable_st_b_XIV,
#line 2043 "./v850/v850.igen"
  itable_st_h_VII,
#line 2049 "./v850/v850.igen"
  itable_st_h_XIV,
#line 2059 "./v850/v850.igen"
  itable_st_w_VII,
#line 2065 "./v850/v850.igen"
  itable_st_w_XIV,
#line 2075 "./v850/v850.igen"
  itable_st_dw_XIV,
#line 2088 "./v850/v850.igen"
  itable_stsr_IX,
#line 2154 "./v850/v850.igen"
  itable_sub_I,
#line 2161 "./v850/v850.igen"
  itable_subr_I,
#line 2168 "./v850/v850.igen"
  itable_switch_I,
#line 2185 "./v850/v850.igen"
  itable_sxb_I,
#line 2199 "./v850/v850.igen"
  itable_sxh_I,
#line 2213 "./v850/v850.igen"
  itable_trap_X,
#line 2220 "./v850/v850.igen"
  itable_tst_I,
#line 2227 "./v850/v850.igen"
  itable_tst1_VIII,
#line 2233 "./v850/v850.igen"
  itable_tst1_IX,
#line 2245 "./v850/v850.igen"
  itable_xor_I,
#line 2252 "./v850/v850.igen"
  itable_xori_VI,
#line 2259 "./v850/v850.igen"
  itable_zxb_I,
#line 2273 "./v850/v850.igen"
  itable_zxh_I,
#line 2288 "./v850/v850.igen"
  itable_break_I,
#line 2295 "./v850/v850.igen"
  itable_dbtrap_I,
#line 2318 "./v850/v850.igen"
  itable_ilgop_X,
#line 2324 "./v850/v850.igen"
  itable_dbret_X,
#line 2367 "./v850/v850.igen"
  itable_absf_d_F_I,
#line 2387 "./v850/v850.igen"
  itable_absf_s_F_I,
#line 2406 "./v850/v850.igen"
  itable_addf_d_F_I,
#line 2428 "./v850/v850.igen"
  itable_addf_s_F_I,
#line 2450 "./v850/v850.igen"
  itable_cmovf_d_F_I,
#line 2481 "./v850/v850.igen"
  itable_cmovf_s_F_I,
#line 2509 "./v850/v850.igen"
  itable_cmpf_d_F_I,
#line 2534 "./v850/v850.igen"
  itable_cmpf_s_F_I,
#line 2559 "./v850/v850.igen"
  itable_cvtf_dl_F_I,
#line 2582 "./v850/v850.igen"
  itable_cvtf_ds_F_I,
#line 2602 "./v850/v850.igen"
  itable_cvtf_dw_F_I,
#line 2624 "./v850/v850.igen"
  itable_cvtf_ld_F_I,
#line 2646 "./v850/v850.igen"
  itable_cvtf_ls_F_I,
#line 2668 "./v850/v850.igen"
  itable_cvtf_sd_F_I,
#line 2687 "./v850/v850.igen"
  itable_cvtf_sl_F_I,
#line 2710 "./v850/v850.igen"
  itable_cvtf_sw_F_I,
#line 2732 "./v850/v850.igen"
  itable_cvtf_wd_F_I,
#line 2751 "./v850/v850.igen"
  itable_cvtf_ws_F_I,
#line 2770 "./v850/v850.igen"
  itable_divf_d_F_I,
#line 2792 "./v850/v850.igen"
  itable_divf_s_F_I,
#line 2814 "./v850/v850.igen"
  itable_maddf_s_F_I,
#line 2838 "./v850/v850.igen"
  itable_fmaf_s_F_I,
#line 2862 "./v850/v850.igen"
  itable_maxf_d_F_I,
#line 2900 "./v850/v850.igen"
  itable_maxf_s_F_I,
#line 2938 "./v850/v850.igen"
  itable_minf_d_F_I,
#line 2976 "./v850/v850.igen"
  itable_minf_s_F_I,
#line 3014 "./v850/v850.igen"
  itable_msubf_s_F_I,
#line 3039 "./v850/v850.igen"
  itable_fmsf_s_F_I,
#line 3064 "./v850/v850.igen"
  itable_mulf_d_F_I,
#line 3086 "./v850/v850.igen"
  itable_mulf_s_F_I,
#line 3108 "./v850/v850.igen"
  itable_negf_d_F_I,
#line 3128 "./v850/v850.igen"
  itable_negf_s_F_I,
#line 3148 "./v850/v850.igen"
  itable_nmaddf_s_F_I,
#line 3174 "./v850/v850.igen"
  itable_fnmaf_s_F_I,
#line 3200 "./v850/v850.igen"
  itable_nmsubf_s_F_I,
#line 3227 "./v850/v850.igen"
  itable_fnmsf_s_F_I,
#line 3254 "./v850/v850.igen"
  itable_recipf_d_F_I,
#line 3275 "./v850/v850.igen"
  itable_recipf_s_F_I,
#line 3296 "./v850/v850.igen"
  itable_rsqrtf_d_F_I,
#line 3320 "./v850/v850.igen"
  itable_rsqrtf_s_F_I,
#line 3344 "./v850/v850.igen"
  itable_sqrtf_d_F_I,
#line 3365 "./v850/v850.igen"
  itable_sqrtf_s_F_I,
#line 3386 "./v850/v850.igen"
  itable_subf_d_F_I,
#line 3408 "./v850/v850.igen"
  itable_subf_s_F_I,
#line 3430 "./v850/v850.igen"
  itable_trfsr_F_I,
#line 3447 "./v850/v850.igen"
  itable_trncf_dl_F_I,
#line 3469 "./v850/v850.igen"
  itable_trncf_dul_F_I,
#line 3491 "./v850/v850.igen"
  itable_trncf_dw_F_I,
#line 3512 "./v850/v850.igen"
  itable_trncf_duw_F_I,
#line 3533 "./v850/v850.igen"
  itable_trncf_sl_F_I,
#line 3552 "./v850/v850.igen"
  itable_trncf_sul_F_I,
#line 3571 "./v850/v850.igen"
  itable_trncf_sw_F_I,
#line 3592 "./v850/v850.igen"
  itable_trncf_suw_F_I,
#line 3613 "./v850/v850.igen"
  itable_rotl_imm_VII,
#line 3622 "./v850/v850.igen"
  itable_rotl_VII,
#line 3632 "./v850/v850.igen"
  itable_bins_top_IX,
#line 3641 "./v850/v850.igen"
  itable_bins_middle_IX,
#line 3650 "./v850/v850.igen"
  itable_bins_bottom_IX,
#line 3659 "./v850/v850.igen"
  itable_cnvq15q30_C,
#line 3676 "./v850/v850.igen"
  itable_cnvq30q15_C,
#line 3693 "./v850/v850.igen"
  itable_cnvq31q62_C,
#line 3710 "./v850/v850.igen"
  itable_cnvq62q31_C,
#line 3727 "./v850/v850.igen"
  itable_dup_h_C,
#line 3749 "./v850/v850.igen"
  itable_dup_w_C,
#line 3769 "./v850/v850.igen"
  itable_expq31_C,
#line 3804 "./v850/v850.igen"
  itable_modadd_C,
#line 3827 "./v850/v850.igen"
  itable_mov_dw_to_gr_C,
#line 3837 "./v850/v850.igen"
  itable_mov_dw_to_vr_C,
#line 3848 "./v850/v850.igen"
  itable_mov_h_C,
#line 3875 "./v850/v850.igen"
  itable_mov_w_vreg_to_vreg_C,
#line 3899 "./v850/v850.igen"
  itable_mov_w_reg_to_vreg_C,
#line 3923 "./v850/v850.igen"
  itable_mov_w_vreg_to_reg_C,
#line 3944 "./v850/v850.igen"
  itable_pki16i32_C,
#line 3967 "./v850/v850.igen"
  itable_pki16ui8_C,
#line 3986 "./v850/v850.igen"
  itable_pki32i16_C,
#line 4013 "./v850/v850.igen"
  itable_pki64i32_C,
#line 4032 "./v850/v850.igen"
  itable_pkq15q31_C,
#line 4050 "./v850/v850.igen"
  itable_pkq30q31_C,
#line 4071 "./v850/v850.igen"
  itable_pkq31q15_C,
#line 4098 "./v850/v850.igen"
  itable_pkui8i16_C,
#line 4121 "./v850/v850.igen"
  itable_vabs_h_C,
#line 4142 "./v850/v850.igen"
  itable_vabs_w_C,
#line 4161 "./v850/v850.igen"
  itable_vadd_dw_C,
#line 4175 "./v850/v850.igen"
  itable_vadd_h_C,
#line 4187 "./v850/v850.igen"
  itable_vadd_w_C,
#line 4199 "./v850/v850.igen"
  itable_vadds_h_C,
#line 4211 "./v850/v850.igen"
  itable_vadds_w_C,
#line 4223 "./v850/v850.igen"
  itable_vaddsat_h_C,
#line 4235 "./v850/v850.igen"
  itable_vaddsat_w_C,
#line 4247 "./v850/v850.igen"
  itable_vand_C,
#line 4258 "./v850/v850.igen"
  itable_vbiq_h_C,
#line 4270 "./v850/v850.igen"
  itable_vbswap_dw_C,
#line 4282 "./v850/v850.igen"
  itable_vbswap_h_C,
#line 4294 "./v850/v850.igen"
  itable_vbswap_w_C,
#line 4306 "./v850/v850.igen"
  itable_vcalc_h_C,
#line 4318 "./v850/v850.igen"
  itable_vcalc_w_C,
#line 4330 "./v850/v850.igen"
  itable_vcmov_C,
  nr_itable_entries,
} itable_index;

typedef enum {
  nr_itable_flags,
} itable_flags;
extern const char * const itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char * const itable_option_names[];

typedef enum {
  itable_processor_v850,
  itable_processor_v850e,
  itable_processor_v850e1,
  itable_processor_v850e2,
  itable_processor_v850e2v3,
  itable_processor_v850e3v5,
  nr_itable_processors,
} itable_processors;
extern const char * const itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  const char *format;
  const char *form;
  const char *flags;
  const char flag[nr_itable_flags + 1];
  const char *options;
  const char option[nr_itable_options + 1];
  const char *processors;
  const char processor[nr_itable_processors + 1];
  const char *name;
  const char *file;
  int line_nr;
} itable_info;

extern const itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 5,
  sizeof_itable_name = 19,
  sizeof_itable_file = 10,
};

#endif /* _ITABLE_H_*/
