/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef SEMANTICS_H
#define SEMANTICS_H

typedef instruction_address idecode_semantic
(SIM_DESC sd,
 idecode_cache *cache_entry,
 instruction_address cia);

typedef instruction_address idecode_semantic_0
(SIM_DESC sd,
 instruction_address cia);

typedef instruction_address idecode_semantic_1
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

typedef instruction_address idecode_semantic_2
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

typedef instruction_address idecode_semantic_3
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_word instruction_2,
 instruction_address cia);

typedef instruction_address idecode_semantic_4
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_word instruction_2,
 instruction_word instruction_3,
 instruction_address cia);


EXTERN_SEMANTICS\
(instruction_address) semantic_mov_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_not_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divh_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sld_bu_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sld_hu_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satsubr_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satsub_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satadd_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulh_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_or_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_xor_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_and_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_tst_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_subr_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sub_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_add_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmp_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satadd_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_add_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmp_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_shr_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sar_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_shl_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulh_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sld_b_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sst_b_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sld_h_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sst_h_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sld_w_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sst_w_IV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_Bcond_III
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_addi_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_movea_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_movhi_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satsubi_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ori_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_xori_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_andi_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulhi_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_b_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_h_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_w_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_b_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_h_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_w_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jarl_V
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_bu_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_hu_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ldsr_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_shr_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_bins_top_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sar_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_bins_middle_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_shl_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_rotl_imm_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_rotl_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_bins_bottom_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_caxi_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mul_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulu_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mul_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulu_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divh_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divhu_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_div_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divu_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divq_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divqu_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmov_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmov_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sbf_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satsub_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_adf_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_satadd_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmovf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_addf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_subf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_maxf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_minf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_fmaf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_fmsf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_fnmaf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_fnmsf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_maddf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_msubf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_nmaddf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_nmsubf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vadd_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vadd_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vadds_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vadds_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vaddsat_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vaddsat_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vadd_dw_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vbiq_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pkq30q31_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pkq31q15_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pki64i32_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pki32i16_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pki16ui8_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pkq15q31_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pki16i32_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_pkui8i16_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vcalc_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vcalc_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vand_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vcmov_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mac_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_macu_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmpf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_stsr_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_shr_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sar_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_shl_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_set1_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_not1_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_clr1_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_tst1_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_setf_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sasf_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_w_vreg_to_vreg_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_bsw_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_bsh_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_hsw_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_hsh_XII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sch0r_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sch1r_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sch0l_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sch1l_IX
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_ws_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_absf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sqrtf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vabs_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_wd_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_sw_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_negf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_recipf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vabs_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_sl_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_rsqrtf_s_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_sd_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_sw_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cnvq15q30_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_sl_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cnvq31q62_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vbswap_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cnvq30q15_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vbswap_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cnvq62q31_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_vbswap_dw_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_w_vreg_to_reg_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_expq31_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_dup_h_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_w_reg_to_vreg_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_suw_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_sul_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_dup_w_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_dw_to_gr_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_dw_to_vr_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmovf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_addf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_subf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mulf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_maxf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_minf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_divf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cmpf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_absf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sqrtf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_modadd_C
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_ls_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_dw_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_ld_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_dl_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_negf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_recipf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_rsqrtf_d_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_ds_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_dw_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_cvtf_dl_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_duw_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trncf_dul_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_fetrap_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_set1_VIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_nop_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_switch_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jmp_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_zxb_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sxb_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_zxh_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_sxh_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_callt_II
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jarl32_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jr32_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_mov_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_dispose_XIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jmp32_VI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jr_V
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_prepare_XIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_prepare00_XIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_prepare01_XIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_prepare10_XIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_prepare11_XIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_b_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_b_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_h_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_w_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_w_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_bu_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_hu_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ld_dw_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_h_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_st_dw_XIV
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_Bcond_VII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trap_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_halt_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_reti_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ctret_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_dbret_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_eiret_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_feret_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_di_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_trfsr_F_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ilgop_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_not1_VIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_clr1_VIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_ei_X
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_tst1_VIII
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_jarl_reg_XI
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_word instruction_1,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_break_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

EXTERN_SEMANTICS\
(instruction_address) semantic_dbtrap_I
(SIM_DESC sd,
 instruction_word instruction_0,
 instruction_address cia);

#endif /* _SEMANTICS_H_*/
