/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef SUPPORT_H
#define SUPPORT_H

#define SD sd
#define CPU (STATE_CPU (sd, 0))
#define CPU_ sd
#define CIA_ cia
#define CIA cia
#define NIA nia

#define SD_ CPU_, CIA_, MY_INDEX
#define _SD SD_ /* deprecated */

INLINE_SUPPORT\
(instruction_address) semantic_illegal
(SIM_DESC sd,
 instruction_address cia);

INLINE_SUPPORT\
(const char *) str_cccc
(SIM_DESC sd, instruction_address cia, int MY_INDEX, int cccc);

INLINE_SUPPORT\
(const char *) str_FFFF
(SIM_DESC sd, instruction_address cia, int MY_INDEX, int FFFF);


#if defined(SUPPORT_INLINE)
# if ((SUPPORT_INLINE & INCLUDE_MODULE)\
      && (SUPPORT_INLINE & INCLUDED_BY_MODULE))
#  include "support.c"
# endif
#endif

#endif /* _SUPPORT_H_*/
