/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef SUPPORT_C
#define SUPPORT_C

#include "sim-main.h"
#include "idecode.h"
#include "itable.h"
#include "support.h"

INLINE_SUPPORT\
(instruction_address)
semantic_illegal
(SIM_DESC sd,
 instruction_address cia)
{
#line 82 "./v850/v850.igen"
  sim_io_eprintf (SD, "Illegal instruction at address 0x%lx\n",
  		  (unsigned long) cia);
  sim_engine_halt (SD, CPU, NULL, cia, sim_signalled, SIM_SIGILL);
  sim_engine_abort (SD, CPU, cia, "Internal function must longjump\n");
  return cia;
}
#line 44 "support.c"

INLINE_SUPPORT\
(const char *)
str_cccc
(SIM_DESC sd, instruction_address cia, int MY_INDEX, int cccc)
{
#line 149 "./v850/v850.igen"
  switch (cccc)
    {
    case 0xf: return "gt";
    case 0xe: return "ge";
    case 0x6: return "lt";

    case 0x7: return "le";

    case 0xb: return "h";
    case 0x9: return "nl";
    case 0x1: return "l";

    case 0x3: return "nh";

    case 0x2: return "e";

    case 0xa: return "ne";

    case 0x0: return "v";
    case 0x8: return "nv";
    case 0x4: return "n";
    case 0xc: return "p";
      /* case 0x1: return "c"; */
      /* case 0x9: return "nc"; */
      /* case 0x2: return "z"; */
      /* case 0xa: return "nz"; */
    case 0x5: return "r"; /* always */
    case 0xd: return "sa";
    }
  return "(null)";
}
#line 83 "support.c"

INLINE_SUPPORT\
(const char *)
str_FFFF
(SIM_DESC sd, instruction_address cia, int MY_INDEX, int FFFF)
{
#line 2344 "./v850/v850.igen"
  switch (FFFF)
    {
    case 0: return "f";
    case 1: return "un";
    case 2: return "eq";
    case 3: return "ueq";
    case 4: return "olt";
    case 5: return "ult";
    case 6: return "ole";
    case 7: return "ule";
    case 8: return "sf";
    case 9: return "ngle";
    case 10: return "seq";
    case 11: return "ngl";
    case 12: return "lt";
    case 13: return "nge";
    case 14: return "le";
    case 15: return "ngt";
    }
  return "(null)";
}
#line 112 "support.c"


#endif /* _SUPPORT_C_*/
