void OP_20_8 (SIM_DESC, SIM_CPU *);		/* andb */
void OP_20B_C (SIM_DESC, SIM_CPU *);		/* andb */
void OP_21_8 (SIM_DESC, SIM_CPU *);		/* andb */
void OP_20B_C (SIM_DESC, SIM_CPU *);		/* andb */
void OP_22_8 (SIM_DESC, SIM_CPU *);		/* andw */
void OP_22B_C (SIM_DESC, SIM_CPU *);		/* andw */
void OP_23_8 (SIM_DESC, SIM_CPU *);		/* andw */
void OP_22B_C (SIM_DESC, SIM_CPU *);		/* andw */
void OP_24_8 (SIM_DESC, SIM_CPU *);		/* orb */
void OP_24B_C (SIM_DESC, SIM_CPU *);		/* orb */
void OP_25_8 (SIM_DESC, SIM_CPU *);		/* orb */
void OP_24B_C (SIM_DESC, SIM_CPU *);		/* orb */
void OP_26_8 (SIM_DESC, SIM_CPU *);		/* orw */
void OP_26B_C (SIM_DESC, SIM_CPU *);		/* orw */
void OP_27_8 (SIM_DESC, SIM_CPU *);		/* orw */
void OP_26B_C (SIM_DESC, SIM_CPU *);		/* orw */
void OP_28_8 (SIM_DESC, SIM_CPU *);		/* xorb */
void OP_28B_C (SIM_DESC, SIM_CPU *);		/* xorb */
void OP_29_8 (SIM_DESC, SIM_CPU *);		/* xorb */
void OP_28B_C (SIM_DESC, SIM_CPU *);		/* xorb */
void OP_2A_8 (SIM_DESC, SIM_CPU *);		/* xorw */
void OP_2AB_C (SIM_DESC, SIM_CPU *);		/* xorw */
void OP_2B_8 (SIM_DESC, SIM_CPU *);		/* xorw */
void OP_2AB_C (SIM_DESC, SIM_CPU *);		/* xorw */
void OP_2C_8 (SIM_DESC, SIM_CPU *);		/* addub */
void OP_2CB_C (SIM_DESC, SIM_CPU *);		/* addub */
void OP_2D_8 (SIM_DESC, SIM_CPU *);		/* addub */
void OP_2E_8 (SIM_DESC, SIM_CPU *);		/* adduw */
void OP_2EB_C (SIM_DESC, SIM_CPU *);		/* adduw */
void OP_2F_8 (SIM_DESC, SIM_CPU *);		/* adduw */
void OP_30_8 (SIM_DESC, SIM_CPU *);		/* addb */
void OP_30B_C (SIM_DESC, SIM_CPU *);		/* addb */
void OP_31_8 (SIM_DESC, SIM_CPU *);		/* addb */
void OP_32_8 (SIM_DESC, SIM_CPU *);		/* addw */
void OP_32B_C (SIM_DESC, SIM_CPU *);		/* addw */
void OP_33_8 (SIM_DESC, SIM_CPU *);		/* addw */
void OP_34_8 (SIM_DESC, SIM_CPU *);		/* addcb */
void OP_34B_C (SIM_DESC, SIM_CPU *);		/* addcb */
void OP_35_8 (SIM_DESC, SIM_CPU *);		/* addcb */
void OP_36_8 (SIM_DESC, SIM_CPU *);		/* addcw */
void OP_36B_C (SIM_DESC, SIM_CPU *);		/* addcw */
void OP_37_8 (SIM_DESC, SIM_CPU *);		/* addcw */
void OP_38_8 (SIM_DESC, SIM_CPU *);		/* subb */
void OP_38B_C (SIM_DESC, SIM_CPU *);		/* subb */
void OP_39_8 (SIM_DESC, SIM_CPU *);		/* subb */
void OP_3A_8 (SIM_DESC, SIM_CPU *);		/* subw */
void OP_3AB_C (SIM_DESC, SIM_CPU *);		/* subw */
void OP_3B_8 (SIM_DESC, SIM_CPU *);		/* subw */
void OP_3C_8 (SIM_DESC, SIM_CPU *);		/* subcb */
void OP_3CB_C (SIM_DESC, SIM_CPU *);		/* subcb */
void OP_3D_8 (SIM_DESC, SIM_CPU *);		/* subcb */
void OP_3E_8 (SIM_DESC, SIM_CPU *);		/* subcw */
void OP_3EB_C (SIM_DESC, SIM_CPU *);		/* subcw */
void OP_3F_8 (SIM_DESC, SIM_CPU *);		/* subcw */
void OP_50_8 (SIM_DESC, SIM_CPU *);		/* cmpb */
void OP_50B_C (SIM_DESC, SIM_CPU *);		/* cmpb */
void OP_51_8 (SIM_DESC, SIM_CPU *);		/* cmpb */
void OP_52_8 (SIM_DESC, SIM_CPU *);		/* cmpw */
void OP_52B_C (SIM_DESC, SIM_CPU *);		/* cmpw */
void OP_53_8 (SIM_DESC, SIM_CPU *);		/* cmpw */
void OP_58_8 (SIM_DESC, SIM_CPU *);		/* movb */
void OP_58B_C (SIM_DESC, SIM_CPU *);		/* movb */
void OP_59_8 (SIM_DESC, SIM_CPU *);		/* movb */
void OP_5A_8 (SIM_DESC, SIM_CPU *);		/* movw */
void OP_5AB_C (SIM_DESC, SIM_CPU *);		/* movw */
void OP_5B_8 (SIM_DESC, SIM_CPU *);		/* movw */
void OP_64_8 (SIM_DESC, SIM_CPU *);		/* mulb */
void OP_64B_C (SIM_DESC, SIM_CPU *);		/* mulb */
void OP_65_8 (SIM_DESC, SIM_CPU *);		/* mulb */
void OP_66_8 (SIM_DESC, SIM_CPU *);		/* mulw */
void OP_66B_C (SIM_DESC, SIM_CPU *);		/* mulw */
void OP_67_8 (SIM_DESC, SIM_CPU *);		/* mulw */
void OP_5C_8 (SIM_DESC, SIM_CPU *);		/* movxb */
void OP_5D_8 (SIM_DESC, SIM_CPU *);		/* movzb */
void OP_B_8 (SIM_DESC, SIM_CPU *);		/* mulsb */
void OP_5E_8 (SIM_DESC, SIM_CPU *);		/* movxw */
void OP_5F_8 (SIM_DESC, SIM_CPU *);		/* movzw */
void OP_62_8 (SIM_DESC, SIM_CPU *);		/* mulsw */
void OP_63_8 (SIM_DESC, SIM_CPU *);		/* muluw */
void OP_54_8 (SIM_DESC, SIM_CPU *);		/* movd */
void OP_54B_C (SIM_DESC, SIM_CPU *);		/* movd */
void OP_55_8 (SIM_DESC, SIM_CPU *);		/* movd */
void OP_5_8 (SIM_DESC, SIM_CPU *);		/* movd */
void OP_7_C (SIM_DESC, SIM_CPU *);		/* movd */
void OP_60_8 (SIM_DESC, SIM_CPU *);		/* addd */
void OP_60B_C (SIM_DESC, SIM_CPU *);		/* addd */
void OP_61_8 (SIM_DESC, SIM_CPU *);		/* addd */
void OP_4_8 (SIM_DESC, SIM_CPU *);		/* addd */
void OP_2_C (SIM_DESC, SIM_CPU *);		/* addd */
void OP_3_C (SIM_DESC, SIM_CPU *);		/* subd */
void OP_14C_14 (SIM_DESC, SIM_CPU *);		/* subd */
void OP_56_8 (SIM_DESC, SIM_CPU *);		/* cmpd */
void OP_56B_C (SIM_DESC, SIM_CPU *);		/* cmpd */
void OP_57_8 (SIM_DESC, SIM_CPU *);		/* cmpd */
void OP_9_C (SIM_DESC, SIM_CPU *);		/* cmpd */
void OP_4_C (SIM_DESC, SIM_CPU *);		/* andd */
void OP_14B_14 (SIM_DESC, SIM_CPU *);		/* andd */
void OP_5_C (SIM_DESC, SIM_CPU *);		/* ord */
void OP_149_14 (SIM_DESC, SIM_CPU *);		/* ord */
void OP_6_C (SIM_DESC, SIM_CPU *);		/* xord */
void OP_14A_14 (SIM_DESC, SIM_CPU *);		/* xord */
void OP_80_9 (SIM_DESC, SIM_CPU *);		/* ashub */
void OP_81_9 (SIM_DESC, SIM_CPU *);		/* ashub */
void OP_41_8 (SIM_DESC, SIM_CPU *);		/* ashub */
void OP_26_7 (SIM_DESC, SIM_CPU *);		/* ashud */
void OP_27_7 (SIM_DESC, SIM_CPU *);		/* ashud */
void OP_48_8 (SIM_DESC, SIM_CPU *);		/* ashud */
void OP_42_8 (SIM_DESC, SIM_CPU *);		/* ashuw */
void OP_43_8 (SIM_DESC, SIM_CPU *);		/* ashuw */
void OP_45_8 (SIM_DESC, SIM_CPU *);		/* ashuw */
void OP_13_9 (SIM_DESC, SIM_CPU *);		/* lshb */
void OP_44_8 (SIM_DESC, SIM_CPU *);		/* lshb */
void OP_25_7 (SIM_DESC, SIM_CPU *);		/* lshd */
void OP_47_8 (SIM_DESC, SIM_CPU *);		/* lshd */
void OP_49_8 (SIM_DESC, SIM_CPU *);		/* lshw */
void OP_46_8 (SIM_DESC, SIM_CPU *);		/* lshw */
void OP_1_4 (SIM_DESC, SIM_CPU *);		/* b */
void OP_18_8 (SIM_DESC, SIM_CPU *);		/* b */
void OP_10_10 (SIM_DESC, SIM_CPU *);		/* b */
void OP_C_8 (SIM_DESC, SIM_CPU *);		/* beq0b */
void OP_D_8 (SIM_DESC, SIM_CPU *);		/* bne0b */
void OP_E_8 (SIM_DESC, SIM_CPU *);		/* beq0w */
void OP_F_8 (SIM_DESC, SIM_CPU *);		/* bne0w */
void OP_A0_C (SIM_DESC, SIM_CPU *);		/* jeq */
void OP_A1_C (SIM_DESC, SIM_CPU *);		/* jne */
void OP_A2_C (SIM_DESC, SIM_CPU *);		/* jcs */
void OP_A3_C (SIM_DESC, SIM_CPU *);		/* jcc */
void OP_A4_C (SIM_DESC, SIM_CPU *);		/* jhi */
void OP_A5_C (SIM_DESC, SIM_CPU *);		/* jls */
void OP_A6_C (SIM_DESC, SIM_CPU *);		/* jgt */
void OP_A7_C (SIM_DESC, SIM_CPU *);		/* jle */
void OP_A8_C (SIM_DESC, SIM_CPU *);		/* jfs */
void OP_A9_C (SIM_DESC, SIM_CPU *);		/* jfc */
void OP_AA_C (SIM_DESC, SIM_CPU *);		/* jlo */
void OP_AB_C (SIM_DESC, SIM_CPU *);		/* jhs */
void OP_AC_C (SIM_DESC, SIM_CPU *);		/* jlt */
void OP_AD_C (SIM_DESC, SIM_CPU *);		/* jge */
void OP_AE_C (SIM_DESC, SIM_CPU *);		/* jump */
void OP_AF_C (SIM_DESC, SIM_CPU *);		/* jusr */
void OP_80_C (SIM_DESC, SIM_CPU *);		/* seq */
void OP_81_C (SIM_DESC, SIM_CPU *);		/* sne */
void OP_82_C (SIM_DESC, SIM_CPU *);		/* scs */
void OP_83_C (SIM_DESC, SIM_CPU *);		/* scc */
void OP_84_C (SIM_DESC, SIM_CPU *);		/* shi */
void OP_85_C (SIM_DESC, SIM_CPU *);		/* sls */
void OP_86_C (SIM_DESC, SIM_CPU *);		/* sgt */
void OP_87_C (SIM_DESC, SIM_CPU *);		/* sle */
void OP_88_C (SIM_DESC, SIM_CPU *);		/* sfs */
void OP_89_C (SIM_DESC, SIM_CPU *);		/* sfc */
void OP_8A_C (SIM_DESC, SIM_CPU *);		/* slo */
void OP_8B_C (SIM_DESC, SIM_CPU *);		/* shs */
void OP_8C_C (SIM_DESC, SIM_CPU *);		/* slt */
void OP_8D_C (SIM_DESC, SIM_CPU *);		/* sge */
void OP_14D_14 (SIM_DESC, SIM_CPU *);		/* macqw */
void OP_14E_14 (SIM_DESC, SIM_CPU *);		/* macuw */
void OP_14F_14 (SIM_DESC, SIM_CPU *);		/* macsw */
void OP_C0_8 (SIM_DESC, SIM_CPU *);		/* bal */
void OP_102_14 (SIM_DESC, SIM_CPU *);		/* bal */
void OP_D_C (SIM_DESC, SIM_CPU *);		/* jal */
void OP_148_14 (SIM_DESC, SIM_CPU *);		/* jal */
void OP_3_9 (SIM_DESC, SIM_CPU *);		/* push */
void OP_1_8 (SIM_DESC, SIM_CPU *);		/* push */
void OP_11E_10 (SIM_DESC, SIM_CPU *);		/* push */
void OP_5_9 (SIM_DESC, SIM_CPU *);		/* pop */
void OP_2_8 (SIM_DESC, SIM_CPU *);		/* pop */
void OP_21E_10 (SIM_DESC, SIM_CPU *);		/* pop */
void OP_7_9 (SIM_DESC, SIM_CPU *);		/* popret */
void OP_3_8 (SIM_DESC, SIM_CPU *);		/* popret */
void OP_31E_10 (SIM_DESC, SIM_CPU *);		/* popret */
void OP_14_D (SIM_DESC, SIM_CPU *);		/* loadm */
void OP_15_D (SIM_DESC, SIM_CPU *);		/* loadmp */
void OP_16_D (SIM_DESC, SIM_CPU *);		/* storm */
void OP_17_D (SIM_DESC, SIM_CPU *);		/* stormp */
void OP_140_14 (SIM_DESC, SIM_CPU *);		/* lpr */
void OP_141_14 (SIM_DESC, SIM_CPU *);		/* lprd */
void OP_142_14 (SIM_DESC, SIM_CPU *);		/* spr */
void OP_143_14 (SIM_DESC, SIM_CPU *);		/* sprd */
void OP_C_C (SIM_DESC, SIM_CPU *);		/* excp */
void OP_D7_9 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_107_14 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_68_8 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_1AA_A (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_104_14 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_D4_9 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_D6_9 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_105_14 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_106_14 (SIM_DESC, SIM_CPU *);		/* cbitb */
void OP_E7_9 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_10B_14 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_70_8 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_1CA_A (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_108_14 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_E4_9 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_E6_9 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_109_14 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_10A_14 (SIM_DESC, SIM_CPU *);		/* sbitb */
void OP_F7_9 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_10F_14 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_78_8 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_1EA_A (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_10C_14 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_F4_9 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_F6_9 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_10D_14 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_10E_14 (SIM_DESC, SIM_CPU *);		/* tbitb */
void OP_6F_8 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_117_14 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_36_7 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_1AB_A (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_114_14 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_6E_8 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_69_8 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_115_14 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_116_14 (SIM_DESC, SIM_CPU *);		/* cbitw */
void OP_77_8 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_11B_14 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_3A_7 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_1CB_A (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_118_14 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_76_8 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_71_8 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_119_14 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_11A_14 (SIM_DESC, SIM_CPU *);		/* sbitw */
void OP_7F_8 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_11F_14 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_3E_7 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_1EB_A (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_11C_14 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_7E_8 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_79_8 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_11D_14 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_11E_14 (SIM_DESC, SIM_CPU *);		/* tbitw */
void OP_6_8 (SIM_DESC, SIM_CPU *);		/* tbit */
void OP_7_8 (SIM_DESC, SIM_CPU *);		/* tbit */
void OP_88_8 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_127_14 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_45_7 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_B_4 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_BE_8 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_219_A (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_184_14 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_124_14 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_BF_8 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_125_14 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_185_14 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_126_14 (SIM_DESC, SIM_CPU *);		/* loadb */
void OP_87_8 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_12B_14 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_46_7 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_A_4 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_AE_8 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_21A_A (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_188_14 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_128_14 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_AF_8 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_129_14 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_189_14 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_12A_14 (SIM_DESC, SIM_CPU *);		/* loadd */
void OP_89_8 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_12F_14 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_47_7 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_9_4 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_9E_8 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_21B_A (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_18C_14 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_12C_14 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_9F_8 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_12D_14 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_18D_14 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_12E_14 (SIM_DESC, SIM_CPU *);		/* loadw */
void OP_C8_8 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_137_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_65_7 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_F_4 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_FE_8 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_319_A (SIM_DESC, SIM_CPU *);		/* storb */
void OP_194_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_134_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_FF_8 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_135_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_195_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_136_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_81_8 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_123_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_42_7 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_218_A (SIM_DESC, SIM_CPU *);		/* storb */
void OP_82_8 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_120_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_83_8 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_121_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_122_14 (SIM_DESC, SIM_CPU *);		/* storb */
void OP_C7_8 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_13B_14 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_66_7 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_E_4 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_EE_8 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_31A_A (SIM_DESC, SIM_CPU *);		/* stord */
void OP_198_14 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_138_14 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_EF_8 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_139_14 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_199_14 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_13A_14 (SIM_DESC, SIM_CPU *);		/* stord */
void OP_C9_8 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_13F_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_67_7 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_D_4 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_DE_8 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_31B_A (SIM_DESC, SIM_CPU *);		/* storw */
void OP_19C_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_13C_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_DF_8 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_13D_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_19D_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_13E_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_C1_8 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_133_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_62_7 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_318_A (SIM_DESC, SIM_CPU *);		/* storw */
void OP_C2_8 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_130_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_C3_8 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_131_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_132_14 (SIM_DESC, SIM_CPU *);		/* storw */
void OP_A_10 (SIM_DESC, SIM_CPU *);		/* cinv[i] */
void OP_B_10 (SIM_DESC, SIM_CPU *);		/* cinv[i,u] */
void OP_C_10 (SIM_DESC, SIM_CPU *);		/* cinv[d] */
void OP_D_10 (SIM_DESC, SIM_CPU *);		/* cinv[d,u] */
void OP_E_10 (SIM_DESC, SIM_CPU *);		/* cinv[d,i] */
void OP_F_10 (SIM_DESC, SIM_CPU *);		/* cinv[d,i,u] */
void OP_2C00_10 (SIM_DESC, SIM_CPU *);		/* nop */
void OP_3_10 (SIM_DESC, SIM_CPU *);		/* retx */
void OP_4_10 (SIM_DESC, SIM_CPU *);		/* di */
void OP_5_10 (SIM_DESC, SIM_CPU *);		/* ei */
void OP_6_10 (SIM_DESC, SIM_CPU *);		/* wait */
void OP_7_10 (SIM_DESC, SIM_CPU *);		/* eiwait */
void OP_0_20 (SIM_DESC, SIM_CPU *);		/* (null) */
