void OP_4607 (SIM_DESC, SIM_CPU *);		/* abs */
void OP_5607 (SIM_DESC, SIM_CPU *);		/* abs */
void OP_200 (SIM_DESC, SIM_CPU *);		/* add */
void OP_1201 (SIM_DESC, SIM_CPU *);		/* add */
void OP_1203 (SIM_DESC, SIM_CPU *);		/* add */
void OP_1200 (SIM_DESC, SIM_CPU *);		/* add2w */
void OP_1000000 (SIM_DESC, SIM_CPU *);		/* add3 */
void OP_17000200 (SIM_DESC, SIM_CPU *);		/* addac3 */
void OP_17000202 (SIM_DESC, SIM_CPU *);		/* addac3 */
void OP_17001200 (SIM_DESC, SIM_CPU *);		/* addac3s */
void OP_17001202 (SIM_DESC, SIM_CPU *);		/* addac3s */
void OP_201 (SIM_DESC, SIM_CPU *);		/* addi */
void OP_C00 (SIM_DESC, SIM_CPU *);		/* and */
void OP_6000000 (SIM_DESC, SIM_CPU *);		/* and3 */
void OP_C01 (SIM_DESC, SIM_CPU *);		/* bclri */
void OP_4900 (SIM_DESC, SIM_CPU *);		/* bl.s */
void OP_24800000 (SIM_DESC, SIM_CPU *);		/* bl.l */
void OP_A01 (SIM_DESC, SIM_CPU *);		/* bnoti */
void OP_4800 (SIM_DESC, SIM_CPU *);		/* bra.s */
void OP_24000000 (SIM_DESC, SIM_CPU *);		/* bra.l */
void OP_4A00 (SIM_DESC, SIM_CPU *);		/* brf0f.s */
void OP_25000000 (SIM_DESC, SIM_CPU *);		/* brf0f.l */
void OP_4B00 (SIM_DESC, SIM_CPU *);		/* brf0t.s */
void OP_25800000 (SIM_DESC, SIM_CPU *);		/* brf0t.l */
void OP_801 (SIM_DESC, SIM_CPU *);		/* bseti */
void OP_E01 (SIM_DESC, SIM_CPU *);		/* btsti */
void OP_5601 (SIM_DESC, SIM_CPU *);		/* clrac */
void OP_600 (SIM_DESC, SIM_CPU *);		/* cmp */
void OP_1603 (SIM_DESC, SIM_CPU *);		/* cmp */
void OP_400 (SIM_DESC, SIM_CPU *);		/* cmpeq */
void OP_1403 (SIM_DESC, SIM_CPU *);		/* cmpeq */
void OP_401 (SIM_DESC, SIM_CPU *);		/* cmpeqi.s */
void OP_2000000 (SIM_DESC, SIM_CPU *);		/* cmpeqi.l */
void OP_601 (SIM_DESC, SIM_CPU *);		/* cmpi.s */
void OP_3000000 (SIM_DESC, SIM_CPU *);		/* cmpi.l */
void OP_4600 (SIM_DESC, SIM_CPU *);		/* cmpu */
void OP_23000000 (SIM_DESC, SIM_CPU *);		/* cmpui */
void OP_4E0F (SIM_DESC, SIM_CPU *);		/* cpfg */
void OP_4E09 (SIM_DESC, SIM_CPU *);		/* cpfg */
void OP_5F20 (SIM_DESC, SIM_CPU *);		/* dbt */
void OP_14002800 (SIM_DESC, SIM_CPU *);		/* divs */
void OP_4E04 (SIM_DESC, SIM_CPU *);		/* exef0f */
void OP_4E24 (SIM_DESC, SIM_CPU *);		/* exef0t */
void OP_4E40 (SIM_DESC, SIM_CPU *);		/* exef1f */
void OP_4E42 (SIM_DESC, SIM_CPU *);		/* exef1t */
void OP_4E00 (SIM_DESC, SIM_CPU *);		/* exefaf */
void OP_4E02 (SIM_DESC, SIM_CPU *);		/* exefat */
void OP_4E20 (SIM_DESC, SIM_CPU *);		/* exetaf */
void OP_4E22 (SIM_DESC, SIM_CPU *);		/* exetat */
void OP_15002A00 (SIM_DESC, SIM_CPU *);		/* exp */
void OP_15002A02 (SIM_DESC, SIM_CPU *);		/* exp */
void OP_4D00 (SIM_DESC, SIM_CPU *);		/* jl */
void OP_4C00 (SIM_DESC, SIM_CPU *);		/* jmp */
void OP_30000000 (SIM_DESC, SIM_CPU *);		/* ld */
void OP_6401 (SIM_DESC, SIM_CPU *);		/* ld */
void OP_6001 (SIM_DESC, SIM_CPU *);		/* ld */
void OP_6000 (SIM_DESC, SIM_CPU *);		/* ld */
void OP_32010000 (SIM_DESC, SIM_CPU *);		/* ld */
void OP_31000000 (SIM_DESC, SIM_CPU *);		/* ld2w */
void OP_6601 (SIM_DESC, SIM_CPU *);		/* ld2w */
void OP_6201 (SIM_DESC, SIM_CPU *);		/* ld2w */
void OP_6200 (SIM_DESC, SIM_CPU *);		/* ld2w */
void OP_33010000 (SIM_DESC, SIM_CPU *);		/* ld2w */
void OP_38000000 (SIM_DESC, SIM_CPU *);		/* ldb */
void OP_7000 (SIM_DESC, SIM_CPU *);		/* ldb */
void OP_4001 (SIM_DESC, SIM_CPU *);		/* ldi.s */
void OP_20000000 (SIM_DESC, SIM_CPU *);		/* ldi.l */
void OP_39000000 (SIM_DESC, SIM_CPU *);		/* ldub */
void OP_7200 (SIM_DESC, SIM_CPU *);		/* ldub */
void OP_2A00 (SIM_DESC, SIM_CPU *);		/* mac */
void OP_1A00 (SIM_DESC, SIM_CPU *);		/* macsu */
void OP_3A00 (SIM_DESC, SIM_CPU *);		/* macu */
void OP_2600 (SIM_DESC, SIM_CPU *);		/* max */
void OP_3600 (SIM_DESC, SIM_CPU *);		/* max */
void OP_3602 (SIM_DESC, SIM_CPU *);		/* max */
void OP_2601 (SIM_DESC, SIM_CPU *);		/* min */
void OP_3601 (SIM_DESC, SIM_CPU *);		/* min */
void OP_3603 (SIM_DESC, SIM_CPU *);		/* min */
void OP_2800 (SIM_DESC, SIM_CPU *);		/* msb */
void OP_1800 (SIM_DESC, SIM_CPU *);		/* msbsu */
void OP_3800 (SIM_DESC, SIM_CPU *);		/* msbu */
void OP_2E00 (SIM_DESC, SIM_CPU *);		/* mul */
void OP_2C00 (SIM_DESC, SIM_CPU *);		/* mulx */
void OP_1C00 (SIM_DESC, SIM_CPU *);		/* mulxsu */
void OP_3C00 (SIM_DESC, SIM_CPU *);		/* mulxu */
void OP_4000 (SIM_DESC, SIM_CPU *);		/* mv */
void OP_5000 (SIM_DESC, SIM_CPU *);		/* mv2w */
void OP_3E00 (SIM_DESC, SIM_CPU *);		/* mv2wfac */
void OP_3E01 (SIM_DESC, SIM_CPU *);		/* mv2wtac */
void OP_3E03 (SIM_DESC, SIM_CPU *);		/* mvac */
void OP_5400 (SIM_DESC, SIM_CPU *);		/* mvb */
void OP_4400 (SIM_DESC, SIM_CPU *);		/* mvf0f */
void OP_4401 (SIM_DESC, SIM_CPU *);		/* mvf0t */
void OP_1E04 (SIM_DESC, SIM_CPU *);		/* mvfacg */
void OP_1E00 (SIM_DESC, SIM_CPU *);		/* mvfachi */
void OP_1E02 (SIM_DESC, SIM_CPU *);		/* mvfaclo */
void OP_5200 (SIM_DESC, SIM_CPU *);		/* mvfc */
void OP_1E41 (SIM_DESC, SIM_CPU *);		/* mvtacg */
void OP_1E01 (SIM_DESC, SIM_CPU *);		/* mvtachi */
void OP_1E21 (SIM_DESC, SIM_CPU *);		/* mvtaclo */
void OP_5600 (SIM_DESC, SIM_CPU *);		/* mvtc */
void OP_5401 (SIM_DESC, SIM_CPU *);		/* mvub */
void OP_4605 (SIM_DESC, SIM_CPU *);		/* neg */
void OP_5605 (SIM_DESC, SIM_CPU *);		/* neg */
void OP_5E00 (SIM_DESC, SIM_CPU *);		/* nop */
void OP_4603 (SIM_DESC, SIM_CPU *);		/* not */
void OP_800 (SIM_DESC, SIM_CPU *);		/* or */
void OP_4000000 (SIM_DESC, SIM_CPU *);		/* or3 */
void OP_5209 (SIM_DESC, SIM_CPU *);		/* sac */
void OP_4209 (SIM_DESC, SIM_CPU *);		/* sachi */
void OP_5201 (SIM_DESC, SIM_CPU *);		/* rac */
void OP_4201 (SIM_DESC, SIM_CPU *);		/* rachi */
void OP_27000000 (SIM_DESC, SIM_CPU *);		/* rep */
void OP_2F000000 (SIM_DESC, SIM_CPU *);		/* repi */
void OP_5F60 (SIM_DESC, SIM_CPU *);		/* rtd */
void OP_5F40 (SIM_DESC, SIM_CPU *);		/* rte */
void OP_1223 (SIM_DESC, SIM_CPU *);		/* sadd */
void OP_4611 (SIM_DESC, SIM_CPU *);		/* setf0f */
void OP_4613 (SIM_DESC, SIM_CPU *);		/* setf0t */
void OP_3220 (SIM_DESC, SIM_CPU *);		/* slae */
void OP_5FC0 (SIM_DESC, SIM_CPU *);		/* sleep */
void OP_2200 (SIM_DESC, SIM_CPU *);		/* sll */
void OP_3200 (SIM_DESC, SIM_CPU *);		/* sll */
void OP_2201 (SIM_DESC, SIM_CPU *);		/* slli */
void OP_3201 (SIM_DESC, SIM_CPU *);		/* slli */
void OP_460B (SIM_DESC, SIM_CPU *);		/* slx */
void OP_2400 (SIM_DESC, SIM_CPU *);		/* sra */
void OP_3400 (SIM_DESC, SIM_CPU *);		/* sra */
void OP_2401 (SIM_DESC, SIM_CPU *);		/* srai */
void OP_3401 (SIM_DESC, SIM_CPU *);		/* srai */
void OP_2000 (SIM_DESC, SIM_CPU *);		/* srl */
void OP_3000 (SIM_DESC, SIM_CPU *);		/* srl */
void OP_2001 (SIM_DESC, SIM_CPU *);		/* srli */
void OP_3001 (SIM_DESC, SIM_CPU *);		/* srli */
void OP_4609 (SIM_DESC, SIM_CPU *);		/* srx */
void OP_34000000 (SIM_DESC, SIM_CPU *);		/* st */
void OP_6800 (SIM_DESC, SIM_CPU *);		/* st */
void OP_6C1F (SIM_DESC, SIM_CPU *);		/* st */
void OP_6801 (SIM_DESC, SIM_CPU *);		/* st */
void OP_6C01 (SIM_DESC, SIM_CPU *);		/* st */
void OP_36010000 (SIM_DESC, SIM_CPU *);		/* st */
void OP_35000000 (SIM_DESC, SIM_CPU *);		/* st2w */
void OP_6A00 (SIM_DESC, SIM_CPU *);		/* st2w */
void OP_6E1F (SIM_DESC, SIM_CPU *);		/* st2w */
void OP_6A01 (SIM_DESC, SIM_CPU *);		/* st2w */
void OP_6E01 (SIM_DESC, SIM_CPU *);		/* st2w */
void OP_37010000 (SIM_DESC, SIM_CPU *);		/* st2w */
void OP_3C000000 (SIM_DESC, SIM_CPU *);		/* stb */
void OP_7800 (SIM_DESC, SIM_CPU *);		/* stb */
void OP_5FE0 (SIM_DESC, SIM_CPU *);		/* stop */
void OP_0 (SIM_DESC, SIM_CPU *);		/* sub */
void OP_1001 (SIM_DESC, SIM_CPU *);		/* sub */
void OP_1003 (SIM_DESC, SIM_CPU *);		/* sub */
void OP_1000 (SIM_DESC, SIM_CPU *);		/* sub2w */
void OP_17000000 (SIM_DESC, SIM_CPU *);		/* subac3 */
void OP_17000002 (SIM_DESC, SIM_CPU *);		/* subac3 */
void OP_17001000 (SIM_DESC, SIM_CPU *);		/* subac3s */
void OP_17001002 (SIM_DESC, SIM_CPU *);		/* subac3s */
void OP_1 (SIM_DESC, SIM_CPU *);		/* subi */
void OP_5F00 (SIM_DESC, SIM_CPU *);		/* trap */
void OP_7000000 (SIM_DESC, SIM_CPU *);		/* tst0i */
void OP_F000000 (SIM_DESC, SIM_CPU *);		/* tst1i */
void OP_5F80 (SIM_DESC, SIM_CPU *);		/* wait */
void OP_A00 (SIM_DESC, SIM_CPU *);		/* xor */
void OP_5000000 (SIM_DESC, SIM_CPU *);		/* xor3 */
