/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 99 "./mips/mips.igen"
  itable_RSVD_SPECIAL,
#line 1821 "./mips/mips.igen"
  itable_ADD_SPECIAL,
#line 1843 "./mips/mips.igen"
  itable_ADDI_NORMAL,
#line 1872 "./mips/mips.igen"
  itable_ADDIU_NORMAL,
#line 1903 "./mips/mips.igen"
  itable_ADDU_SPECIAL,
#line 1932 "./mips/mips.igen"
  itable_AND_SPECIAL,
#line 1954 "./mips/mips.igen"
  itable_ANDI_NORMAL,
#line 1976 "./mips/mips.igen"
  itable_BEQ_NORMAL,
#line 2011 "./mips/mips.igen"
  itable_BEQL_NORMAL,
#line 2036 "./mips/mips.igen"
  itable_BGEZ_REGIMM,
#line 2062 "./mips/mips.igen"
  itable_BGEZAL_REGIMM,
#line 2097 "./mips/mips.igen"
  itable_BGEZALL_REGIMM,
#line 2127 "./mips/mips.igen"
  itable_BGEZL_REGIMM,
#line 2152 "./mips/mips.igen"
  itable_BGTZ_NORMAL,
#line 2178 "./mips/mips.igen"
  itable_BGTZL_NORMAL,
#line 2205 "./mips/mips.igen"
  itable_BLEZ_NORMAL,
#line 2233 "./mips/mips.igen"
  itable_BLEZL_NORMAL,
#line 2258 "./mips/mips.igen"
  itable_BLTZ_REGIMM,
#line 2284 "./mips/mips.igen"
  itable_BLTZAL_REGIMM,
#line 2325 "./mips/mips.igen"
  itable_BLTZALL_REGIMM,
#line 2353 "./mips/mips.igen"
  itable_BLTZL_REGIMM,
#line 2380 "./mips/mips.igen"
  itable_BNE_NORMAL,
#line 2406 "./mips/mips.igen"
  itable_BNEL_NORMAL,
#line 2431 "./mips/mips.igen"
  itable_BREAK_SPECIAL,
#line 2483 "./mips/mips.igen"
  itable_DADD_SPECIAL,
#line 2500 "./mips/mips.igen"
  itable_DADDI_NORMAL,
#line 2523 "./mips/mips.igen"
  itable_DADDIU_NORMAL,
#line 2547 "./mips/mips.igen"
  itable_DADDU_SPECIAL,
#line 2626 "./mips/mips.igen"
  itable_DDIV_SPECIAL,
#line 2667 "./mips/mips.igen"
  itable_DDIVU_SPECIAL,
#line 2707 "./mips/mips.igen"
  itable_DIV_SPECIAL,
#line 2748 "./mips/mips.igen"
  itable_DIVU_SPECIAL,
#line 2832 "./mips/mips.igen"
  itable_DMULT_SPECIAL,
#line 2861 "./mips/mips.igen"
  itable_DMULTU_SPECIAL,
#line 2936 "./mips/mips.igen"
  itable_DSLL_SPECIAL,
#line 2952 "./mips/mips.igen"
  itable_DSLL32_SPECIAL,
#line 2975 "./mips/mips.igen"
  itable_DSLLV_SPECIAL,
#line 2998 "./mips/mips.igen"
  itable_DSRA_SPECIAL,
#line 3014 "./mips/mips.igen"
  itable_DSRA32_SPECIAL,
#line 3038 "./mips/mips.igen"
  itable_DSRAV_SPECIAL,
#line 3061 "./mips/mips.igen"
  itable_DSRL_SPECIAL,
#line 3077 "./mips/mips.igen"
  itable_DSRL32_SPECIAL,
#line 3103 "./mips/mips.igen"
  itable_DSRLV_SPECIAL,
#line 3119 "./mips/mips.igen"
  itable_DSUB_SPECIAL,
#line 3142 "./mips/mips.igen"
  itable_DSUBU_SPECIAL,
#line 3158 "./mips/mips.igen"
  itable_J_NORMAL,
#line 3182 "./mips/mips.igen"
  itable_JAL_NORMAL,
#line 3206 "./mips/mips.igen"
  itable_JALR_SPECIAL,
#line 3242 "./mips/mips.igen"
  itable_JR_SPECIAL,
#line 3376 "./mips/mips.igen"
  itable_LB_NORMAL,
#line 3397 "./mips/mips.igen"
  itable_LBU_NORMAL,
#line 3418 "./mips/mips.igen"
  itable_LD_NORMAL,
#line 3434 "./mips/mips.igen"
  itable_LDCz_NORMAL,
#line 3454 "./mips/mips.igen"
  itable_LDL_NORMAL,
#line 3469 "./mips/mips.igen"
  itable_LDR_NORMAL,
#line 3484 "./mips/mips.igen"
  itable_LH_NORMAL,
#line 3505 "./mips/mips.igen"
  itable_LHU_NORMAL,
#line 3526 "./mips/mips.igen"
  itable_LL_NORMAL,
#line 3543 "./mips/mips.igen"
  itable_LLD_NORMAL,
#line 3558 "./mips/mips.igen"
  itable_LUI_NORMAL,
#line 3579 "./mips/mips.igen"
  itable_LW_NORMAL,
#line 3600 "./mips/mips.igen"
  itable_LWCz_NORMAL,
#line 3619 "./mips/mips.igen"
  itable_LWL_NORMAL,
#line 3638 "./mips/mips.igen"
  itable_LWR_NORMAL,
#line 3657 "./mips/mips.igen"
  itable_LWU_NORMAL,
#line 3723 "./mips/mips.igen"
  itable_MFHI_SPECIAL,
#line 3759 "./mips/mips.igen"
  itable_MFLO_SPECIAL,
#line 3787 "./mips/mips.igen"
  itable_MOVN_SPECIAL,
#line 3802 "./mips/mips.igen"
  itable_MOVZ_SPECIAL,
#line 3859 "./mips/mips.igen"
  itable_MTHI_SPECIAL,
#line 3887 "./mips/mips.igen"
  itable_MTLO_SPECIAL,
#line 3945 "./mips/mips.igen"
  itable_MULT_SPECIAL,
#line 3997 "./mips/mips.igen"
  itable_MULTU_SPECIAL,
#line 4040 "./mips/mips.igen"
  itable_NOR_SPECIAL,
#line 4068 "./mips/mips.igen"
  itable_OR_SPECIAL,
#line 4097 "./mips/mips.igen"
  itable_ORI_NORMAL,
#line 4118 "./mips/mips.igen"
  itable_PREF_NORMAL,
#line 4254 "./mips/mips.igen"
  itable_SB_NORMAL,
#line 4275 "./mips/mips.igen"
  itable_SC_NORMAL,
#line 4292 "./mips/mips.igen"
  itable_SCD_NORMAL,
#line 4307 "./mips/mips.igen"
  itable_SD_NORMAL,
#line 4323 "./mips/mips.igen"
  itable_SDCz_NORMAL,
#line 4340 "./mips/mips.igen"
  itable_SDL_NORMAL,
#line 4355 "./mips/mips.igen"
  itable_SDR_NORMAL,
#line 4371 "./mips/mips.igen"
  itable_SH_NORMAL,
#line 4400 "./mips/mips.igen"
  itable_SLLa_SPECIAL,
#line 4443 "./mips/mips.igen"
  itable_SLLV_SPECIAL,
#line 4471 "./mips/mips.igen"
  itable_SLT_SPECIAL,
#line 4499 "./mips/mips.igen"
  itable_SLTI_NORMAL,
#line 4527 "./mips/mips.igen"
  itable_SLTIU_NORMAL,
#line 4556 "./mips/mips.igen"
  itable_SLTU_SPECIAL,
#line 4587 "./mips/mips.igen"
  itable_SRA_SPECIAL,
#line 4620 "./mips/mips.igen"
  itable_SRAV_SPECIAL,
#line 4652 "./mips/mips.igen"
  itable_SRL_SPECIAL,
#line 4684 "./mips/mips.igen"
  itable_SRLV_SPECIAL,
#line 4705 "./mips/mips.igen"
  itable_SUB_SPECIAL,
#line 4735 "./mips/mips.igen"
  itable_SUBU_SPECIAL,
#line 4756 "./mips/mips.igen"
  itable_SW_NORMAL,
#line 4777 "./mips/mips.igen"
  itable_SWCz_NORMAL,
#line 4796 "./mips/mips.igen"
  itable_SWL_NORMAL,
#line 4815 "./mips/mips.igen"
  itable_SWR_NORMAL,
#line 4834 "./mips/mips.igen"
  itable_SYNC_SPECIAL,
#line 4855 "./mips/mips.igen"
  itable_SYSCALL_SPECIAL,
#line 4876 "./mips/mips.igen"
  itable_TEQ_SPECIAL,
#line 4895 "./mips/mips.igen"
  itable_TEQI_REGIMM,
#line 4912 "./mips/mips.igen"
  itable_TGE_SPECIAL,
#line 4931 "./mips/mips.igen"
  itable_TGEI_REGIMM,
#line 4948 "./mips/mips.igen"
  itable_TGEIU_REGIMM,
#line 4965 "./mips/mips.igen"
  itable_TGEU_SPECIAL,
#line 4984 "./mips/mips.igen"
  itable_TLT_SPECIAL,
#line 5003 "./mips/mips.igen"
  itable_TLTI_REGIMM,
#line 5020 "./mips/mips.igen"
  itable_TLTIU_REGIMM,
#line 5037 "./mips/mips.igen"
  itable_TLTU_SPECIAL,
#line 5056 "./mips/mips.igen"
  itable_TNE_SPECIAL,
#line 5075 "./mips/mips.igen"
  itable_TNEI_REGIMM,
#line 5099 "./mips/mips.igen"
  itable_XOR_SPECIAL,
#line 5127 "./mips/mips.igen"
  itable_XORI_NORMAL,
#line 5369 "./mips/mips.igen"
  itable_ABS_fmt_COP1,
#line 5391 "./mips/mips.igen"
  itable_ADD_fmt_COP1,
#line 5453 "./mips/mips.igen"
  itable_BC1b_COP1S,
#line 5491 "./mips/mips.igen"
  itable_C_cond_fmtb_COP1,
#line 5508 "./mips/mips.igen"
  itable_CEIL_L_fmt_COP1,
#line 5526 "./mips/mips.igen"
  itable_CEIL_W_COP1,
#line 5560 "./mips/mips.igen"
  itable_CFC1b_COP1,
#line 5603 "./mips/mips.igen"
  itable_CTC1b_COP1,
#line 5634 "./mips/mips.igen"
  itable_CVT_D_fmt_COP1,
#line 5655 "./mips/mips.igen"
  itable_CVT_L_fmt_COP1,
#line 5687 "./mips/mips.igen"
  itable_CVT_S_fmt_COP1,
#line 5730 "./mips/mips.igen"
  itable_CVT_W_fmt_COP1,
#line 5751 "./mips/mips.igen"
  itable_DIV_fmt_COP1,
#line 5789 "./mips/mips.igen"
  itable_DMFC1b_COP1,
#line 5825 "./mips/mips.igen"
  itable_DMTC1b_COP1,
#line 5842 "./mips/mips.igen"
  itable_FLOOR_L_fmt_COP1,
#line 5860 "./mips/mips.igen"
  itable_FLOOR_W_fmt_COP1,
#line 5892 "./mips/mips.igen"
  itable_LDC1b_COP1,
#line 5918 "./mips/mips.igen"
  itable_LDXC1_COP1X,
#line 5952 "./mips/mips.igen"
  itable_LWC1_COP1,
#line 5973 "./mips/mips.igen"
  itable_LWXC1_COP1X,
#line 5987 "./mips/mips.igen"
  itable_MADD_fmt_COP1X,
#line 6013 "./mips/mips.igen"
  itable_MFC1b_COP1,
#line 6031 "./mips/mips.igen"
  itable_MOV_fmt_COP1,
#line 6054 "./mips/mips.igen"
  itable_MOVtf_SPECIAL,
#line 6070 "./mips/mips.igen"
  itable_MOVtf_fmt_COP1,
#line 6084 "./mips/mips.igen"
  itable_MOVN_fmt_COP1,
#line 6105 "./mips/mips.igen"
  itable_MOVZ_fmt_COP1,
#line 6119 "./mips/mips.igen"
  itable_MSUB_fmt_COP1X,
#line 6146 "./mips/mips.igen"
  itable_MTC1b_COP1,
#line 6164 "./mips/mips.igen"
  itable_MUL_fmt_COP1,
#line 6185 "./mips/mips.igen"
  itable_NEG_fmt_COP1,
#line 6206 "./mips/mips.igen"
  itable_NMADD_fmt_COP1X,
#line 6219 "./mips/mips.igen"
  itable_NMSUB_fmt_COP1X,
#line 6254 "./mips/mips.igen"
  itable_PREFX_COP1X,
#line 6289 "./mips/mips.igen"
  itable_RECIP_fmt_COP1,
#line 6304 "./mips/mips.igen"
  itable_ROUND_L_fmt_COP1,
#line 6322 "./mips/mips.igen"
  itable_ROUND_W_fmt_COP1,
#line 6342 "./mips/mips.igen"
  itable_RSQRT_fmt_COP1,
#line 6368 "./mips/mips.igen"
  itable_SDC1b_COP1,
#line 6394 "./mips/mips.igen"
  itable_SDXC1_COP1X,
#line 6428 "./mips/mips.igen"
  itable_SQRT_fmt_COP1,
#line 6448 "./mips/mips.igen"
  itable_SUB_fmt_COP1,
#line 6470 "./mips/mips.igen"
  itable_SWC1_COP1,
#line 6491 "./mips/mips.igen"
  itable_SWXC1_COP1X,
#line 6504 "./mips/mips.igen"
  itable_TRUNC_L_fmt_COP1,
#line 6522 "./mips/mips.igen"
  itable_TRUNC_W_COP1,
#line 6549 "./mips/mips.igen"
  itable_BC0F_COP0,
#line 6574 "./mips/mips.igen"
  itable_BC0FL_COP0,
#line 6591 "./mips/mips.igen"
  itable_BC0T_COP0,
#line 6607 "./mips/mips.igen"
  itable_BC0TL_COP0,
#line 6634 "./mips/mips.igen"
  itable_CACHE_NORMAL,
#line 6651 "./mips/mips.igen"
  itable_DMFC0_COP0,
#line 6665 "./mips/mips.igen"
  itable_DMTC0_COP0,
#line 6679 "./mips/mips.igen"
  itable_ERET_COP0,
#line 6708 "./mips/mips.igen"
  itable_MFC0_COP0,
#line 6730 "./mips/mips.igen"
  itable_MTC0_COP0,
#line 6751 "./mips/mips.igen"
  itable_RFE_COP0,
#line 6766 "./mips/mips.igen"
  itable_COPz_NORMAL,
#line 6787 "./mips/mips.igen"
  itable_TLBP_COP0,
#line 6804 "./mips/mips.igen"
  itable_TLBR_COP0,
#line 6821 "./mips/mips.igen"
  itable_TLBWI_COP0,
#line 6838 "./mips/mips.igen"
  itable_TLBWR_COP0,
  nr_itable_entries,
} itable_index;

typedef enum {
  itable_flag_32,
  itable_flag_64,
  itable_flag_f,
  nr_itable_flags,
} itable_flags;
extern const char * const itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char * const itable_option_names[];

typedef enum {
  itable_processor_dsp,
  itable_processor_dsp2,
  itable_processor_mdmx,
  itable_processor_micromips32,
  itable_processor_micromips64,
  itable_processor_micromipsdsp,
  itable_processor_mips16,
  itable_processor_mips16e,
  itable_processor_mips32,
  itable_processor_mips32r2,
  itable_processor_mips32r6,
  itable_processor_mips3d,
  itable_processor_mips64,
  itable_processor_mips64r2,
  itable_processor_mips64r6,
  itable_processor_mipsI,
  itable_processor_mipsII,
  itable_processor_mipsIII,
  itable_processor_mipsIV,
  itable_processor_mipsV,
  itable_processor_r3900,
  itable_processor_sb1,
  itable_processor_smartmips,
  itable_processor_vr4100,
  itable_processor_vr4120,
  itable_processor_vr5000,
  itable_processor_vr5400,
  itable_processor_vr5500,
  nr_itable_processors,
} itable_processors;
extern const char * const itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  const char *format;
  const char *form;
  const char *flags;
  const char flag[nr_itable_flags + 1];
  const char *options;
  const char option[nr_itable_options + 1];
  const char *processors;
  const char processor[nr_itable_processors + 1];
  const char *name;
  const char *file;
  int line_nr;
} itable_info;

extern const itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 8,
  sizeof_itable_name = 12,
  sizeof_itable_file = 10,
};

#endif /* _ITABLE_H_*/
