/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 17 "./mn10300/mn10300.igen"
  itable_mov_S0i,
#line 30 "./mn10300/mn10300.igen"
  itable_mov_S0,
#line 43 "./mn10300/mn10300.igen"
  itable_mov_D0,
#line 56 "./mn10300/mn10300.igen"
  itable_mov_D0a,
#line 69 "./mn10300/mn10300.igen"
  itable_mov_S0ai,
#line 82 "./mn10300/mn10300.igen"
  itable_mov_S0a,
#line 95 "./mn10300/mn10300.igen"
  itable_mov_S0b,
#line 108 "./mn10300/mn10300.igen"
  itable_mov_D0b,
#line 121 "./mn10300/mn10300.igen"
  itable_mov_D0c,
#line 134 "./mn10300/mn10300.igen"
  itable_mov_D0d,
#line 147 "./mn10300/mn10300.igen"
  itable_mov_D0e,
#line 160 "./mn10300/mn10300.igen"
  itable_mov_D0f,
#line 173 "./mn10300/mn10300.igen"
  itable_mov_S0c,
#line 186 "./mn10300/mn10300.igen"
  itable_mov_D1,
#line 200 "./mn10300/mn10300.igen"
  itable_mov_D2,
#line 214 "./mn10300/mn10300.igen"
  itable_mov_D4,
#line 229 "./mn10300/mn10300.igen"
  itable_mov_S1,
#line 242 "./mn10300/mn10300.igen"
  itable_mov_D2a,
#line 256 "./mn10300/mn10300.igen"
  itable_mov_D4a,
#line 270 "./mn10300/mn10300.igen"
  itable_mov_D0g,
#line 284 "./mn10300/mn10300.igen"
  itable_mov_S2,
#line 296 "./mn10300/mn10300.igen"
  itable_mov_D4b,
#line 309 "./mn10300/mn10300.igen"
  itable_mov_D0h,
#line 322 "./mn10300/mn10300.igen"
  itable_mov_D1a,
#line 336 "./mn10300/mn10300.igen"
  itable_mov_D2b,
#line 351 "./mn10300/mn10300.igen"
  itable_mov_D4c,
#line 366 "./mn10300/mn10300.igen"
  itable_mov_S1a,
#line 380 "./mn10300/mn10300.igen"
  itable_mov_D2c,
#line 394 "./mn10300/mn10300.igen"
  itable_mov_D4d,
#line 409 "./mn10300/mn10300.igen"
  itable_mov_D0i,
#line 424 "./mn10300/mn10300.igen"
  itable_mov_D2d,
#line 437 "./mn10300/mn10300.igen"
  itable_mov_D4e,
#line 451 "./mn10300/mn10300.igen"
  itable_mov_D1b,
#line 465 "./mn10300/mn10300.igen"
  itable_mov_S0d,
#line 478 "./mn10300/mn10300.igen"
  itable_mov_D1c,
#line 492 "./mn10300/mn10300.igen"
  itable_mov_D2e,
#line 506 "./mn10300/mn10300.igen"
  itable_mov_D4f,
#line 521 "./mn10300/mn10300.igen"
  itable_mov_S1b,
#line 534 "./mn10300/mn10300.igen"
  itable_mov_D2f,
#line 548 "./mn10300/mn10300.igen"
  itable_mov_D4g,
#line 562 "./mn10300/mn10300.igen"
  itable_mov_D0j,
#line 576 "./mn10300/mn10300.igen"
  itable_mov_S2a,
#line 589 "./mn10300/mn10300.igen"
  itable_mov_D4h,
#line 603 "./mn10300/mn10300.igen"
  itable_mov_D0k,
#line 616 "./mn10300/mn10300.igen"
  itable_mov_D1d,
#line 630 "./mn10300/mn10300.igen"
  itable_mov_D2g,
#line 644 "./mn10300/mn10300.igen"
  itable_mov_D4i,
#line 659 "./mn10300/mn10300.igen"
  itable_mov_S1c,
#line 674 "./mn10300/mn10300.igen"
  itable_mov_D2h,
#line 690 "./mn10300/mn10300.igen"
  itable_mov_D4j,
#line 706 "./mn10300/mn10300.igen"
  itable_mov_D0l,
#line 722 "./mn10300/mn10300.igen"
  itable_mov_D2i,
#line 738 "./mn10300/mn10300.igen"
  itable_mov_D4k,
#line 754 "./mn10300/mn10300.igen"
  itable_mov_D1e,
#line 770 "./mn10300/mn10300.igen"
  itable_mov_S2b,
#line 788 "./mn10300/mn10300.igen"
  itable_mov_D4l,
#line 806 "./mn10300/mn10300.igen"
  itable_mov_S2c,
#line 824 "./mn10300/mn10300.igen"
  itable_mov_D4m,
#line 839 "./mn10300/mn10300.igen"
  itable_movbu_D0,
#line 855 "./mn10300/mn10300.igen"
  itable_movbu_D1f,
#line 871 "./mn10300/mn10300.igen"
  itable_movbu_D2,
#line 888 "./mn10300/mn10300.igen"
  itable_movbu_D4,
#line 905 "./mn10300/mn10300.igen"
  itable_movbu_D1a,
#line 921 "./mn10300/mn10300.igen"
  itable_movbu_D2a,
#line 938 "./mn10300/mn10300.igen"
  itable_movbu_D4a,
#line 955 "./mn10300/mn10300.igen"
  itable_movbu_D0a,
#line 972 "./mn10300/mn10300.igen"
  itable_movbu_S2,
#line 987 "./mn10300/mn10300.igen"
  itable_movbu_D4b,
#line 1003 "./mn10300/mn10300.igen"
  itable_movbu_D0b,
#line 1018 "./mn10300/mn10300.igen"
  itable_movbu_D1b,
#line 1034 "./mn10300/mn10300.igen"
  itable_movbu_D2b,
#line 1050 "./mn10300/mn10300.igen"
  itable_movbu_D4c,
#line 1067 "./mn10300/mn10300.igen"
  itable_movbu_D1c,
#line 1082 "./mn10300/mn10300.igen"
  itable_movbu_D2c,
#line 1098 "./mn10300/mn10300.igen"
  itable_movbu_D4d,
#line 1114 "./mn10300/mn10300.igen"
  itable_movbu_D0c,
#line 1130 "./mn10300/mn10300.igen"
  itable_movbu_S2a,
#line 1146 "./mn10300/mn10300.igen"
  itable_movbu_D4e,
#line 1162 "./mn10300/mn10300.igen"
  itable_movhu_D0,
#line 1178 "./mn10300/mn10300.igen"
  itable_movhu_D1d,
#line 1194 "./mn10300/mn10300.igen"
  itable_movhu_D2,
#line 1211 "./mn10300/mn10300.igen"
  itable_movhu_D4,
#line 1228 "./mn10300/mn10300.igen"
  itable_movhu_D1a,
#line 1244 "./mn10300/mn10300.igen"
  itable_movhu_D2a,
#line 1260 "./mn10300/mn10300.igen"
  itable_movhu_D4a,
#line 1276 "./mn10300/mn10300.igen"
  itable_movhu_D0a,
#line 1292 "./mn10300/mn10300.igen"
  itable_movhu_S2,
#line 1307 "./mn10300/mn10300.igen"
  itable_movhu_D4b,
#line 1323 "./mn10300/mn10300.igen"
  itable_movhu_D0b,
#line 1339 "./mn10300/mn10300.igen"
  itable_movhu_D1b,
#line 1355 "./mn10300/mn10300.igen"
  itable_movhu_D2b,
#line 1371 "./mn10300/mn10300.igen"
  itable_movhu_D4c,
#line 1388 "./mn10300/mn10300.igen"
  itable_movhu_D1c,
#line 1404 "./mn10300/mn10300.igen"
  itable_movhu_D2c,
#line 1420 "./mn10300/mn10300.igen"
  itable_movhu_D4d,
#line 1436 "./mn10300/mn10300.igen"
  itable_movhu_D0c,
#line 1452 "./mn10300/mn10300.igen"
  itable_movhu_S2a,
#line 1467 "./mn10300/mn10300.igen"
  itable_movhu_D4e,
#line 1483 "./mn10300/mn10300.igen"
  itable_ext_D0,
#line 1501 "./mn10300/mn10300.igen"
  itable_extb_S0,
#line 1516 "./mn10300/mn10300.igen"
  itable_extbu_S0,
#line 1531 "./mn10300/mn10300.igen"
  itable_exth_S0,
#line 1546 "./mn10300/mn10300.igen"
  itable_exthu_S0,
#line 1561 "./mn10300/mn10300.igen"
  itable_clr_S0,
#line 1579 "./mn10300/mn10300.igen"
  itable_add_S0,
#line 1593 "./mn10300/mn10300.igen"
  itable_add_D0,
#line 1608 "./mn10300/mn10300.igen"
  itable_add_D0a,
#line 1623 "./mn10300/mn10300.igen"
  itable_add_D0b,
#line 1638 "./mn10300/mn10300.igen"
  itable_add_S1,
#line 1653 "./mn10300/mn10300.igen"
  itable_add_D2,
#line 1668 "./mn10300/mn10300.igen"
  itable_add_D4,
#line 1683 "./mn10300/mn10300.igen"
  itable_add_S1a,
#line 1698 "./mn10300/mn10300.igen"
  itable_add_D2a,
#line 1713 "./mn10300/mn10300.igen"
  itable_add_D4a,
#line 1728 "./mn10300/mn10300.igen"
  itable_add_D1,
#line 1747 "./mn10300/mn10300.igen"
  itable_add_D2b,
#line 1766 "./mn10300/mn10300.igen"
  itable_add_D4b,
#line 1785 "./mn10300/mn10300.igen"
  itable_addc_D0,
#line 1816 "./mn10300/mn10300.igen"
  itable_sub_D0,
#line 1830 "./mn10300/mn10300.igen"
  itable_sub_D0a,
#line 1845 "./mn10300/mn10300.igen"
  itable_sub_D0b,
#line 1860 "./mn10300/mn10300.igen"
  itable_sub_D0c,
#line 1875 "./mn10300/mn10300.igen"
  itable_sub_D4,
#line 1890 "./mn10300/mn10300.igen"
  itable_sub_D4a,
#line 1905 "./mn10300/mn10300.igen"
  itable_subc_D0,
#line 1936 "./mn10300/mn10300.igen"
  itable_mul_D0,
#line 1961 "./mn10300/mn10300.igen"
  itable_mulu_D0,
#line 1986 "./mn10300/mn10300.igen"
  itable_div_D0,
#line 2024 "./mn10300/mn10300.igen"
  itable_divu_D0,
#line 2061 "./mn10300/mn10300.igen"
  itable_inc_S0,
#line 2079 "./mn10300/mn10300.igen"
  itable_inc_S0a,
#line 2094 "./mn10300/mn10300.igen"
  itable_inc4_S0,
#line 2109 "./mn10300/mn10300.igen"
  itable_cmp_S0i,
#line 2124 "./mn10300/mn10300.igen"
  itable_cmp_S0,
#line 2139 "./mn10300/mn10300.igen"
  itable_cmp_D0,
#line 2154 "./mn10300/mn10300.igen"
  itable_cmp_D0a,
#line 2169 "./mn10300/mn10300.igen"
  itable_cmp_S0ai,
#line 2185 "./mn10300/mn10300.igen"
  itable_cmp_S0a,
#line 2200 "./mn10300/mn10300.igen"
  itable_cmp_D2,
#line 2216 "./mn10300/mn10300.igen"
  itable_cmp_D4,
#line 2232 "./mn10300/mn10300.igen"
  itable_cmp_D2a,
#line 2248 "./mn10300/mn10300.igen"
  itable_cmp_D4a,
#line 2264 "./mn10300/mn10300.igen"
  itable_and_D0,
#line 2285 "./mn10300/mn10300.igen"
  itable_and_D1,
#line 2306 "./mn10300/mn10300.igen"
  itable_and_D2,
#line 2327 "./mn10300/mn10300.igen"
  itable_and_D4,
#line 2349 "./mn10300/mn10300.igen"
  itable_and_D2a,
#line 2365 "./mn10300/mn10300.igen"
  itable_or_D0,
#line 2380 "./mn10300/mn10300.igen"
  itable_or_D1,
#line 2395 "./mn10300/mn10300.igen"
  itable_or_D2,
#line 2410 "./mn10300/mn10300.igen"
  itable_or_D4,
#line 2425 "./mn10300/mn10300.igen"
  itable_or_D2a,
#line 2440 "./mn10300/mn10300.igen"
  itable_xor_D0,
#line 2455 "./mn10300/mn10300.igen"
  itable_xor_D2,
#line 2470 "./mn10300/mn10300.igen"
  itable_xor_D4,
#line 2485 "./mn10300/mn10300.igen"
  itable_not_D0,
#line 2506 "./mn10300/mn10300.igen"
  itable_btst_D1,
#line 2521 "./mn10300/mn10300.igen"
  itable_btst_D2,
#line 2536 "./mn10300/mn10300.igen"
  itable_btst_D4,
#line 2552 "./mn10300/mn10300.igen"
  itable_btst_D5,
#line 2569 "./mn10300/mn10300.igen"
  itable_btst_D2a,
#line 2585 "./mn10300/mn10300.igen"
  itable_bset_D0,
#line 2609 "./mn10300/mn10300.igen"
  itable_bset_D5,
#line 2633 "./mn10300/mn10300.igen"
  itable_bset_D2,
#line 2656 "./mn10300/mn10300.igen"
  itable_bclr_D0,
#line 2680 "./mn10300/mn10300.igen"
  itable_bclr_D5,
#line 2704 "./mn10300/mn10300.igen"
  itable_bclr_D2,
#line 2727 "./mn10300/mn10300.igen"
  itable_asr_D0,
#line 2752 "./mn10300/mn10300.igen"
  itable_asr_D1,
#line 2777 "./mn10300/mn10300.igen"
  itable_lsr_D0,
#line 2800 "./mn10300/mn10300.igen"
  itable_lsr_D1,
#line 2822 "./mn10300/mn10300.igen"
  itable_asl_D0,
#line 2844 "./mn10300/mn10300.igen"
  itable_asl_D1,
#line 2865 "./mn10300/mn10300.igen"
  itable_asl2_S0,
#line 2886 "./mn10300/mn10300.igen"
  itable_ror_D0,
#line 2913 "./mn10300/mn10300.igen"
  itable_rol_D0,
#line 2940 "./mn10300/mn10300.igen"
  itable_beq_S1,
#line 2959 "./mn10300/mn10300.igen"
  itable_bne_S1,
#line 2978 "./mn10300/mn10300.igen"
  itable_bgt_S1,
#line 2998 "./mn10300/mn10300.igen"
  itable_bge_S1,
#line 3017 "./mn10300/mn10300.igen"
  itable_ble_S1,
#line 3037 "./mn10300/mn10300.igen"
  itable_blt_S1,
#line 3056 "./mn10300/mn10300.igen"
  itable_bhi_S1,
#line 3075 "./mn10300/mn10300.igen"
  itable_bcc_S1,
#line 3094 "./mn10300/mn10300.igen"
  itable_bls_S1,
#line 3113 "./mn10300/mn10300.igen"
  itable_bcs_S1,
#line 3132 "./mn10300/mn10300.igen"
  itable_bvc_D1,
#line 3151 "./mn10300/mn10300.igen"
  itable_bvs_D1,
#line 3170 "./mn10300/mn10300.igen"
  itable_bnc_D1,
#line 3189 "./mn10300/mn10300.igen"
  itable_bns_D1,
#line 3208 "./mn10300/mn10300.igen"
  itable_bra_S1,
#line 3224 "./mn10300/mn10300.igen"
  itable_leq_S0,
#line 3243 "./mn10300/mn10300.igen"
  itable_lne_S0,
#line 3262 "./mn10300/mn10300.igen"
  itable_lgt_S0,
#line 3282 "./mn10300/mn10300.igen"
  itable_lge_S0,
#line 3301 "./mn10300/mn10300.igen"
  itable_lle_S0,
#line 3321 "./mn10300/mn10300.igen"
  itable_llt_S0,
#line 3340 "./mn10300/mn10300.igen"
  itable_lhi_S0,
#line 3359 "./mn10300/mn10300.igen"
  itable_lcc_S0,
#line 3378 "./mn10300/mn10300.igen"
  itable_lls_S0,
#line 3397 "./mn10300/mn10300.igen"
  itable_lcs_S0,
#line 3416 "./mn10300/mn10300.igen"
  itable_lra_S0,
#line 3432 "./mn10300/mn10300.igen"
  itable_setlb_S0,
#line 3448 "./mn10300/mn10300.igen"
  itable_jmp_D0,
#line 3463 "./mn10300/mn10300.igen"
  itable_jmp_S2,
#line 3478 "./mn10300/mn10300.igen"
  itable_jmp_S4,
#line 3493 "./mn10300/mn10300.igen"
  itable_calls_D0,
#line 3515 "./mn10300/mn10300.igen"
  itable_calls_D2,
#line 3537 "./mn10300/mn10300.igen"
  itable_calls_D4,
#line 3559 "./mn10300/mn10300.igen"
  itable_rets_D0,
#line 3577 "./mn10300/mn10300.igen"
  itable_rti_D0,
#line 3597 "./mn10300/mn10300.igen"
  itable_trap_D0,
#line 3617 "./mn10300/mn10300.igen"
  itable_rtm_D0,
#line 3632 "./mn10300/mn10300.igen"
  itable_nop_S0,
#line 3646 "./mn10300/mn10300.igen"
  itable_putx_D0,
#line 3657 "./mn10300/mn10300.igen"
  itable_getx_D0,
#line 3679 "./mn10300/mn10300.igen"
  itable_mulq_D0,
#line 3704 "./mn10300/mn10300.igen"
  itable_mulq_D1,
#line 3729 "./mn10300/mn10300.igen"
  itable_mulq_D2,
#line 3754 "./mn10300/mn10300.igen"
  itable_mulq_D4,
#line 3779 "./mn10300/mn10300.igen"
  itable_mulqu_D0,
#line 3804 "./mn10300/mn10300.igen"
  itable_mulqu_D1,
#line 3829 "./mn10300/mn10300.igen"
  itable_mulqu_D2,
#line 3854 "./mn10300/mn10300.igen"
  itable_mulqu_D4,
#line 3879 "./mn10300/mn10300.igen"
  itable_sat16_D0,
#line 3899 "./mn10300/mn10300.igen"
  itable_sat24_D0,
#line 3919 "./mn10300/mn10300.igen"
  itable_bsch_D0,
#line 3940 "./mn10300/mn10300.igen"
  itable_syscall_D0,
#line 3955 "./mn10300/mn10300.igen"
  itable_break_S0,
#line 3969 "./mn10300/mn10300.igen"
  itable_movm_S1,
#line 4068 "./mn10300/mn10300.igen"
  itable_movm_S1a,
#line 4167 "./mn10300/mn10300.igen"
  itable_call_S4,
#line 4276 "./mn10300/mn10300.igen"
  itable_call_S6,
#line 4385 "./mn10300/mn10300.igen"
  itable_ret_S2,
#line 4490 "./mn10300/mn10300.igen"
  itable_retf_S2,
#line 42 "./mn10300/am33.igen"
  itable_mov_D0m,
#line 53 "./mn10300/am33.igen"
  itable_mov_D0n,
#line 64 "./mn10300/am33.igen"
  itable_mov_D0o,
#line 75 "./mn10300/am33.igen"
  itable_mov_D0p,
#line 86 "./mn10300/am33.igen"
  itable_mov_D0q,
#line 96 "./mn10300/am33.igen"
  itable_mov_D0r,
#line 106 "./mn10300/am33.igen"
  itable_mov_D0s,
#line 117 "./mn10300/am33.igen"
  itable_syscall_D0t,
#line 135 "./mn10300/am33.igen"
  itable_mov_D0u,
#line 146 "./mn10300/am33.igen"
  itable_mov_D0v,
#line 156 "./mn10300/am33.igen"
  itable_mov_D0w,
#line 168 "./mn10300/am33.igen"
  itable_mov_D0x,
#line 180 "./mn10300/am33.igen"
  itable_mov_D0y,
#line 192 "./mn10300/am33.igen"
  itable_mov_D0z,
#line 205 "./mn10300/am33.igen"
  itable_movm_D1a,
#line 299 "./mn10300/am33.igen"
  itable_movm_D1b,
#line 393 "./mn10300/am33.igen"
  itable_and_4a,
#line 403 "./mn10300/am33.igen"
  itable_or_D4a,
#line 413 "./mn10300/am33.igen"
  itable_mov_D1g,
#line 428 "./mn10300/am33.igen"
  itable_ext_D1,
#line 444 "./mn10300/am33.igen"
  itable_extb_D1,
#line 458 "./mn10300/am33.igen"
  itable_extbu_D1,
#line 472 "./mn10300/am33.igen"
  itable_exth_D1,
#line 486 "./mn10300/am33.igen"
  itable_exthu_D1,
#line 500 "./mn10300/am33.igen"
  itable_clr_D1,
#line 515 "./mn10300/am33.igen"
  itable_add_D1b,
#line 529 "./mn10300/am33.igen"
  itable_addc_D1b,
#line 559 "./mn10300/am33.igen"
  itable_sub_D1b,
#line 573 "./mn10300/am33.igen"
  itable_subc_D1b,
#line 603 "./mn10300/am33.igen"
  itable_inc_D1,
#line 616 "./mn10300/am33.igen"
  itable_inc4_D1,
#line 629 "./mn10300/am33.igen"
  itable_cmp_D1,
#line 643 "./mn10300/am33.igen"
  itable_mov_D1l,
#line 658 "./mn10300/am33.igen"
  itable_mov_D1m,
#line 673 "./mn10300/am33.igen"
  itable_and_D1a,
#line 694 "./mn10300/am33.igen"
  itable_or_D1a,
#line 714 "./mn10300/am33.igen"
  itable_xor_D1a,
#line 734 "./mn10300/am33.igen"
  itable_not_D1,
#line 753 "./mn10300/am33.igen"
  itable_asr_D1a,
#line 777 "./mn10300/am33.igen"
  itable_lsr_D1a,
#line 799 "./mn10300/am33.igen"
  itable_asl_D1a,
#line 819 "./mn10300/am33.igen"
  itable_asl2_D1,
#line 838 "./mn10300/am33.igen"
  itable_ror_D1,
#line 863 "./mn10300/am33.igen"
  itable_rol_D1,
#line 888 "./mn10300/am33.igen"
  itable_mul_D1b,
#line 912 "./mn10300/am33.igen"
  itable_mulu_D1b,
#line 936 "./mn10300/am33.igen"
  itable_div_D1b,
#line 962 "./mn10300/am33.igen"
  itable_divu_D1b,
#line 989 "./mn10300/am33.igen"
  itable_mov_D1h,
#line 1003 "./mn10300/am33.igen"
  itable_mov_D1i,
#line 1017 "./mn10300/am33.igen"
  itable_movbu_D1g,
#line 1031 "./mn10300/am33.igen"
  itable_movbu_D1i,
#line 1045 "./mn10300/am33.igen"
  itable_movhu_D1g,
#line 1059 "./mn10300/am33.igen"
  itable_movhu_D1i,
#line 1073 "./mn10300/am33.igen"
  itable_mov_D1y,
#line 1088 "./mn10300/am33.igen"
  itable_mov_D1z,
#line 1103 "./mn10300/am33.igen"
  itable_mov_D1j,
#line 1116 "./mn10300/am33.igen"
  itable_mov_D1k,
#line 1129 "./mn10300/am33.igen"
  itable_movbu_D1j,
#line 1142 "./mn10300/am33.igen"
  itable_movbu_D1k,
#line 1155 "./mn10300/am33.igen"
  itable_movhu_D1j,
#line 1168 "./mn10300/am33.igen"
  itable_movhu_D1k,
#line 1181 "./mn10300/am33.igen"
  itable_movhu_D1y,
#line 1196 "./mn10300/am33.igen"
  itable_movhu_D1z,
#line 1212 "./mn10300/am33.igen"
  itable_mac_D1,
#line 1241 "./mn10300/am33.igen"
  itable_macu_D1,
#line 1270 "./mn10300/am33.igen"
  itable_macb_D1,
#line 1294 "./mn10300/am33.igen"
  itable_macbu_D1,
#line 1318 "./mn10300/am33.igen"
  itable_mach_D1,
#line 1347 "./mn10300/am33.igen"
  itable_machu_D1,
#line 1376 "./mn10300/am33.igen"
  itable_dmach_D1,
#line 1402 "./mn10300/am33.igen"
  itable_dmachu_D1,
#line 1428 "./mn10300/am33.igen"
  itable_dmulh_D1,
#line 1449 "./mn10300/am33.igen"
  itable_dumachu_D1,
#line 1470 "./mn10300/am33.igen"
  itable_sat16_D1,
#line 1498 "./mn10300/am33.igen"
  itable_mcste_D1,
#line 1596 "./mn10300/am33.igen"
  itable_swap_D1,
#line 1614 "./mn10300/am33.igen"
  itable_swaph_D1,
#line 1632 "./mn10300/am33.igen"
  itable_swhw_D1,
#line 1648 "./mn10300/am33.igen"
  itable_bsch_D1,
#line 1688 "./mn10300/am33.igen"
  itable_mov_D2j,
#line 1701 "./mn10300/am33.igen"
  itable_movu_D2,
#line 1714 "./mn10300/am33.igen"
  itable_add_D2d,
#line 1727 "./mn10300/am33.igen"
  itable_addc_D2d,
#line 1756 "./mn10300/am33.igen"
  itable_sub_D2d,
#line 1770 "./mn10300/am33.igen"
  itable_subc_D2d,
#line 1799 "./mn10300/am33.igen"
  itable_cmp_D2b,
#line 1812 "./mn10300/am33.igen"
  itable_mov_D2k,
#line 1826 "./mn10300/am33.igen"
  itable_and_D2d,
#line 1845 "./mn10300/am33.igen"
  itable_or_D2d,
#line 1864 "./mn10300/am33.igen"
  itable_xor_D2d,
#line 1883 "./mn10300/am33.igen"
  itable_asr_D2a,
#line 1906 "./mn10300/am33.igen"
  itable_lsr_D2a,
#line 1926 "./mn10300/am33.igen"
  itable_asl_D2a,
#line 1945 "./mn10300/am33.igen"
  itable_mul_D2a,
#line 1968 "./mn10300/am33.igen"
  itable_mulu_D2a,
#line 1991 "./mn10300/am33.igen"
  itable_btst_D2l,
#line 2004 "./mn10300/am33.igen"
  itable_mov_D2l,
#line 2018 "./mn10300/am33.igen"
  itable_mov_D2m,
#line 2032 "./mn10300/am33.igen"
  itable_movbu_D2l,
#line 2046 "./mn10300/am33.igen"
  itable_movbu_D2m,
#line 2060 "./mn10300/am33.igen"
  itable_movhu_D2l,
#line 2074 "./mn10300/am33.igen"
  itable_movhu_D2m,
#line 2088 "./mn10300/am33.igen"
  itable_mov_D2y,
#line 2103 "./mn10300/am33.igen"
  itable_mov_D2z,
#line 2119 "./mn10300/am33.igen"
  itable_mov_D2n,
#line 2132 "./mn10300/am33.igen"
  itable_mov_D2o,
#line 2145 "./mn10300/am33.igen"
  itable_movbu_D2n,
#line 2158 "./mn10300/am33.igen"
  itable_movbu_D2o,
#line 2171 "./mn10300/am33.igen"
  itable_movhu_D2n,
#line 2184 "./mn10300/am33.igen"
  itable_movhu_D2o,
#line 2197 "./mn10300/am33.igen"
  itable_movhu_D2y,
#line 2212 "./mn10300/am33.igen"
  itable_movhu_D2z,
#line 2228 "./mn10300/am33.igen"
  itable_mac_D2,
#line 2256 "./mn10300/am33.igen"
  itable_macu_D2,
#line 2284 "./mn10300/am33.igen"
  itable_macb_D2,
#line 2312 "./mn10300/am33.igen"
  itable_macbu_D2,
#line 2340 "./mn10300/am33.igen"
  itable_mach_D2,
#line 2368 "./mn10300/am33.igen"
  itable_machu_D2,
#line 2396 "./mn10300/am33.igen"
  itable_mcste_D2,
#line 2493 "./mn10300/am33.igen"
  itable_add_D2c,
#line 2524 "./mn10300/am33.igen"
  itable_addc_D2c,
#line 2555 "./mn10300/am33.igen"
  itable_sub_D2c,
#line 2586 "./mn10300/am33.igen"
  itable_subc_D2c,
#line 2617 "./mn10300/am33.igen"
  itable_and_D2c,
#line 2640 "./mn10300/am33.igen"
  itable_or_D2c,
#line 2663 "./mn10300/am33.igen"
  itable_xor_D2c,
#line 2686 "./mn10300/am33.igen"
  itable_asr_D2c,
#line 2713 "./mn10300/am33.igen"
  itable_lsr_D2c,
#line 2737 "./mn10300/am33.igen"
  itable_asl_D2c,
#line 2760 "./mn10300/am33.igen"
  itable_mul_D2c,
#line 2788 "./mn10300/am33.igen"
  itable_mulu_D2c,
#line 2816 "./mn10300/am33.igen"
  itable_mov_D2p,
#line 2829 "./mn10300/am33.igen"
  itable_mov_D2q,
#line 2842 "./mn10300/am33.igen"
  itable_movbu_D2p,
#line 2855 "./mn10300/am33.igen"
  itable_movbu_D2q,
#line 2868 "./mn10300/am33.igen"
  itable_movhu_D2p,
#line 2881 "./mn10300/am33.igen"
  itable_movhu_D2q,
#line 2894 "./mn10300/am33.igen"
  itable_mov_D2r,
#line 2909 "./mn10300/am33.igen"
  itable_mov_D2s,
#line 2924 "./mn10300/am33.igen"
  itable_movbu_D2r,
#line 2939 "./mn10300/am33.igen"
  itable_movbu_D2s,
#line 2954 "./mn10300/am33.igen"
  itable_movhu_D2r,
#line 2969 "./mn10300/am33.igen"
  itable_movhu_D2s,
#line 2984 "./mn10300/am33.igen"
  itable_mac_D2c,
#line 3021 "./mn10300/am33.igen"
  itable_macu_D2c,
#line 3058 "./mn10300/am33.igen"
  itable_macb_D2c,
#line 3087 "./mn10300/am33.igen"
  itable_macbu_D2c,
#line 3116 "./mn10300/am33.igen"
  itable_mach_D2c,
#line 3147 "./mn10300/am33.igen"
  itable_machu_D2c,
#line 3178 "./mn10300/am33.igen"
  itable_dmach_D2c,
#line 3209 "./mn10300/am33.igen"
  itable_dmachu_D2c,
#line 3240 "./mn10300/am33.igen"
  itable_dmulh_D2c,
#line 3263 "./mn10300/am33.igen"
  itable_dmulhu_D2c,
#line 3286 "./mn10300/am33.igen"
  itable_sat24_D2,
#line 3314 "./mn10300/am33.igen"
  itable_bsch_D2c,
#line 3354 "./mn10300/am33.igen"
  itable_mov_D4t,
#line 3367 "./mn10300/am33.igen"
  itable_movu_D4k,
#line 3380 "./mn10300/am33.igen"
  itable_add_D4c,
#line 3393 "./mn10300/am33.igen"
  itable_addc_D4b,
#line 3421 "./mn10300/am33.igen"
  itable_sub_D4b,
#line 3434 "./mn10300/am33.igen"
  itable_subc_D4b,
#line 3462 "./mn10300/am33.igen"
  itable_cmp_D4b,
#line 3475 "./mn10300/am33.igen"
  itable_mov_D4o,
#line 3489 "./mn10300/am33.igen"
  itable_and_D4b,
#line 3508 "./mn10300/am33.igen"
  itable_or_D4b,
#line 3527 "./mn10300/am33.igen"
  itable_xor_D4b,
#line 3546 "./mn10300/am33.igen"
  itable_asr_D4b,
#line 3570 "./mn10300/am33.igen"
  itable_lsr_D4b,
#line 3590 "./mn10300/am33.igen"
  itable_asl_D4b,
#line 3609 "./mn10300/am33.igen"
  itable_mul_D4b,
#line 3632 "./mn10300/am33.igen"
  itable_mulu_D4b,
#line 3655 "./mn10300/am33.igen"
  itable_btst_D4p,
#line 3668 "./mn10300/am33.igen"
  itable_mov_D4p,
#line 3684 "./mn10300/am33.igen"
  itable_mov_D4q,
#line 3699 "./mn10300/am33.igen"
  itable_movbu_D4p,
#line 3715 "./mn10300/am33.igen"
  itable_movbu_D4q,
#line 3730 "./mn10300/am33.igen"
  itable_movhu_D4p,
#line 3746 "./mn10300/am33.igen"
  itable_movhu_D4q,
#line 3761 "./mn10300/am33.igen"
  itable_mov_D4y,
#line 3776 "./mn10300/am33.igen"
  itable_mov_D4z,
#line 3792 "./mn10300/am33.igen"
  itable_mov_D4r,
#line 3806 "./mn10300/am33.igen"
  itable_mov_D4s,
#line 3820 "./mn10300/am33.igen"
  itable_movbu_D4r,
#line 3834 "./mn10300/am33.igen"
  itable_movbu_D4s,
#line 3848 "./mn10300/am33.igen"
  itable_movhu_D4r,
#line 3862 "./mn10300/am33.igen"
  itable_movhu_D4s,
#line 3876 "./mn10300/am33.igen"
  itable_movhu_D4y,
#line 3891 "./mn10300/am33.igen"
  itable_movhu_D4z,
#line 3906 "./mn10300/am33.igen"
  itable_mac_D4z,
#line 3934 "./mn10300/am33.igen"
  itable_macu_D4z,
#line 3962 "./mn10300/am33.igen"
  itable_macb_D4z,
#line 3990 "./mn10300/am33.igen"
  itable_macbu_D4z,
#line 4018 "./mn10300/am33.igen"
  itable_mach_D4z,
#line 4046 "./mn10300/am33.igen"
  itable_machu_D4z,
#line 4074 "./mn10300/am33.igen"
  itable_mov_D4u,
#line 4087 "./mn10300/am33.igen"
  itable_mov_D4v,
#line 4101 "./mn10300/am33.igen"
  itable_movbu_D4t,
#line 4114 "./mn10300/am33.igen"
  itable_movbu_D4u,
#line 4128 "./mn10300/am33.igen"
  itable_movhu_D4t,
#line 4141 "./mn10300/am33.igen"
  itable_movhu_D4u,
#line 4155 "./mn10300/am33.igen"
  itable_mov_D5,
#line 4168 "./mn10300/am33.igen"
  itable_movu_D5,
#line 4181 "./mn10300/am33.igen"
  itable_add_D5,
#line 4194 "./mn10300/am33.igen"
  itable_addc_D5,
#line 4223 "./mn10300/am33.igen"
  itable_sub_D5,
#line 4236 "./mn10300/am33.igen"
  itable_subc_D5,
#line 4265 "./mn10300/am33.igen"
  itable_cmp_D5,
#line 4278 "./mn10300/am33.igen"
  itable_mov_D5b,
#line 4292 "./mn10300/am33.igen"
  itable_and_D5,
#line 4311 "./mn10300/am33.igen"
  itable_or_D5,
#line 4330 "./mn10300/am33.igen"
  itable_xor_D5,
#line 4349 "./mn10300/am33.igen"
  itable_asr_D5,
#line 4372 "./mn10300/am33.igen"
  itable_lsr_D5,
#line 4392 "./mn10300/am33.igen"
  itable_asl_D5,
#line 4411 "./mn10300/am33.igen"
  itable_mul_D5,
#line 4434 "./mn10300/am33.igen"
  itable_mulu_D5,
#line 4457 "./mn10300/am33.igen"
  itable_btst_D5a,
#line 4470 "./mn10300/am33.igen"
  itable_mov_D5f,
#line 4485 "./mn10300/am33.igen"
  itable_mov_D5g,
#line 4500 "./mn10300/am33.igen"
  itable_movbu_D5,
#line 4515 "./mn10300/am33.igen"
  itable_movbu_D5b,
#line 4530 "./mn10300/am33.igen"
  itable_movhu_D5,
#line 4545 "./mn10300/am33.igen"
  itable_movhu_D5b,
#line 4560 "./mn10300/am33.igen"
  itable_mov_D5y,
#line 4575 "./mn10300/am33.igen"
  itable_mov_D5z,
#line 4591 "./mn10300/am33.igen"
  itable_mov_D5c,
#line 4605 "./mn10300/am33.igen"
  itable_mov_D5d,
#line 4619 "./mn10300/am33.igen"
  itable_movbu_D5c,
#line 4633 "./mn10300/am33.igen"
  itable_movbu_D5d,
#line 4647 "./mn10300/am33.igen"
  itable_movhu_D5c,
#line 4661 "./mn10300/am33.igen"
  itable_movhu_D5d,
#line 4676 "./mn10300/am33.igen"
  itable_movhu_D5y,
#line 4691 "./mn10300/am33.igen"
  itable_movhu_D5f,
#line 4707 "./mn10300/am33.igen"
  itable_mac_D5,
#line 4736 "./mn10300/am33.igen"
  itable_macu_D5,
#line 4765 "./mn10300/am33.igen"
  itable_macb_D5,
#line 4789 "./mn10300/am33.igen"
  itable_macbu_D5,
#line 4813 "./mn10300/am33.igen"
  itable_mach_D5,
#line 4837 "./mn10300/am33.igen"
  itable_machu_D5,
#line 4861 "./mn10300/am33.igen"
  itable_dmach_D5,
#line 4887 "./mn10300/am33.igen"
  itable_dmachu_D5,
#line 4913 "./mn10300/am33.igen"
  itable_dmulh_D5,
#line 4934 "./mn10300/am33.igen"
  itable_dmulhu_D5,
#line 4955 "./mn10300/am33.igen"
  itable_mov_D5h,
#line 4968 "./mn10300/am33.igen"
  itable_mov_D5e,
#line 4981 "./mn10300/am33.igen"
  itable_movbu_D5i,
#line 4994 "./mn10300/am33.igen"
  itable_movbu_D5e,
#line 5007 "./mn10300/am33.igen"
  itable_movhu_D5j,
#line 5020 "./mn10300/am33.igen"
  itable_movhu_D5e,
#line 5033 "./mn10300/am33.igen"
  itable_add_add_D2,
#line 5053 "./mn10300/am33.igen"
  itable_add_add_D2b,
#line 5072 "./mn10300/am33.igen"
  itable_add_sub_D2,
#line 5092 "./mn10300/am33.igen"
  itable_add_sub_D2b,
#line 5111 "./mn10300/am33.igen"
  itable_add_cmp_D2,
#line 5129 "./mn10300/am33.igen"
  itable_add_cmp_D2b,
#line 5146 "./mn10300/am33.igen"
  itable_add_mov_D2,
#line 5166 "./mn10300/am33.igen"
  itable_add_mov_D2b,
#line 5185 "./mn10300/am33.igen"
  itable_add_asr_D2,
#line 5208 "./mn10300/am33.igen"
  itable_add_asr_D2b,
#line 5230 "./mn10300/am33.igen"
  itable_add_lsr_D2,
#line 5250 "./mn10300/am33.igen"
  itable_add_lsr_D2b,
#line 5270 "./mn10300/am33.igen"
  itable_add_asl_D2,
#line 5290 "./mn10300/am33.igen"
  itable_add_asl_D2b,
#line 5309 "./mn10300/am33.igen"
  itable_cmp_add_D2,
#line 5327 "./mn10300/am33.igen"
  itable_cmp_add_D2b,
#line 5344 "./mn10300/am33.igen"
  itable_cmp_sub_D2,
#line 5362 "./mn10300/am33.igen"
  itable_cmp_sub_D2b,
#line 5379 "./mn10300/am33.igen"
  itable_cmp_mov_D2,
#line 5397 "./mn10300/am33.igen"
  itable_cmp_mov_D2b,
#line 5414 "./mn10300/am33.igen"
  itable_cmp_asr_D2,
#line 5435 "./mn10300/am33.igen"
  itable_cmp_asr_D2b,
#line 5455 "./mn10300/am33.igen"
  itable_cmp_lsr_D2,
#line 5473 "./mn10300/am33.igen"
  itable_cmp_lsr_D2b,
#line 5491 "./mn10300/am33.igen"
  itable_cmp_asl_D2,
#line 5509 "./mn10300/am33.igen"
  itable_cmp_asl_D2b,
#line 5526 "./mn10300/am33.igen"
  itable_sub_add_D2,
#line 5546 "./mn10300/am33.igen"
  itable_sub_add_D2b,
#line 5565 "./mn10300/am33.igen"
  itable_sub_sub_D2,
#line 5585 "./mn10300/am33.igen"
  itable_sub_sub_D2b,
#line 5604 "./mn10300/am33.igen"
  itable_sub_cmp_D2,
#line 5622 "./mn10300/am33.igen"
  itable_sub_cmp_D2b,
#line 5639 "./mn10300/am33.igen"
  itable_sub_mov_D2,
#line 5659 "./mn10300/am33.igen"
  itable_sub_mov_D2b,
#line 5678 "./mn10300/am33.igen"
  itable_sub_asr_D2,
#line 5701 "./mn10300/am33.igen"
  itable_sub_asr_D2b,
#line 5723 "./mn10300/am33.igen"
  itable_sub_lsr_D2,
#line 5743 "./mn10300/am33.igen"
  itable_sub_lsr_D2b,
#line 5763 "./mn10300/am33.igen"
  itable_sub_asl_D2,
#line 5783 "./mn10300/am33.igen"
  itable_sub_asl_D2b,
#line 5802 "./mn10300/am33.igen"
  itable_mov_add_D2,
#line 5822 "./mn10300/am33.igen"
  itable_mov_add_D2b,
#line 5841 "./mn10300/am33.igen"
  itable_mov_sub_D2,
#line 5861 "./mn10300/am33.igen"
  itable_mov_sub_D2b,
#line 5880 "./mn10300/am33.igen"
  itable_mov_cmp_D2,
#line 5898 "./mn10300/am33.igen"
  itable_mov_cmp_D2b,
#line 5915 "./mn10300/am33.igen"
  itable_mov_mov_D2,
#line 5935 "./mn10300/am33.igen"
  itable_mov_mov_D2b,
#line 5954 "./mn10300/am33.igen"
  itable_mov_asr_D2,
#line 5977 "./mn10300/am33.igen"
  itable_mov_asr_D2b,
#line 5999 "./mn10300/am33.igen"
  itable_mov_lsr_D2,
#line 6019 "./mn10300/am33.igen"
  itable_mov_lsr_D2b,
#line 6039 "./mn10300/am33.igen"
  itable_mov_asl_D2,
#line 6059 "./mn10300/am33.igen"
  itable_mov_asl_D2b,
#line 6078 "./mn10300/am33.igen"
  itable_add_add_D2c,
#line 6097 "./mn10300/am33.igen"
  itable_add_add_D2d,
#line 6115 "./mn10300/am33.igen"
  itable_add_sub_D2c,
#line 6134 "./mn10300/am33.igen"
  itable_add_sub_D2d,
#line 6152 "./mn10300/am33.igen"
  itable_add_cmp_D2c,
#line 6169 "./mn10300/am33.igen"
  itable_add_cmp_D2d,
#line 6185 "./mn10300/am33.igen"
  itable_add_mov_D2c,
#line 6204 "./mn10300/am33.igen"
  itable_add_mov_D2d,
#line 6222 "./mn10300/am33.igen"
  itable_add_asr_D2c,
#line 6244 "./mn10300/am33.igen"
  itable_add_asr_D2d,
#line 6265 "./mn10300/am33.igen"
  itable_add_lsr_D2c,
#line 6284 "./mn10300/am33.igen"
  itable_add_lsr_D2d,
#line 6303 "./mn10300/am33.igen"
  itable_add_asl_D2c,
#line 6322 "./mn10300/am33.igen"
  itable_add_asl_D2d,
#line 6340 "./mn10300/am33.igen"
  itable_cmp_add_D2c,
#line 6357 "./mn10300/am33.igen"
  itable_cmp_add_D2d,
#line 6373 "./mn10300/am33.igen"
  itable_cmp_sub_D2c,
#line 6390 "./mn10300/am33.igen"
  itable_cmp_sub_D2d,
#line 6406 "./mn10300/am33.igen"
  itable_cmp_mov_D2c,
#line 6423 "./mn10300/am33.igen"
  itable_cmp_mov_D2d,
#line 6439 "./mn10300/am33.igen"
  itable_cmp_asr_D2c,
#line 6459 "./mn10300/am33.igen"
  itable_cmp_asr_D2d,
#line 6478 "./mn10300/am33.igen"
  itable_cmp_lsr_D2c,
#line 6495 "./mn10300/am33.igen"
  itable_cmp_lsr_D2d,
#line 6512 "./mn10300/am33.igen"
  itable_cmp_asl_D2c,
#line 6529 "./mn10300/am33.igen"
  itable_cmp_asl_D2d,
#line 6545 "./mn10300/am33.igen"
  itable_sub_add_D2c,
#line 6564 "./mn10300/am33.igen"
  itable_sub_add_D2d,
#line 6582 "./mn10300/am33.igen"
  itable_sub_sub_D2c,
#line 6601 "./mn10300/am33.igen"
  itable_sub_sub_D2d,
#line 6619 "./mn10300/am33.igen"
  itable_sub_cmp_D2c,
#line 6636 "./mn10300/am33.igen"
  itable_sub_cmp_D2d,
#line 6652 "./mn10300/am33.igen"
  itable_sub_mov_D2c,
#line 6671 "./mn10300/am33.igen"
  itable_sub_mov_D2d,
#line 6689 "./mn10300/am33.igen"
  itable_sub_asr_D2c,
#line 6711 "./mn10300/am33.igen"
  itable_sub_asr_D2d,
#line 6732 "./mn10300/am33.igen"
  itable_sub_lsr_D2c,
#line 6751 "./mn10300/am33.igen"
  itable_sub_lsr_D2d,
#line 6770 "./mn10300/am33.igen"
  itable_sub_asl_D2c,
#line 6789 "./mn10300/am33.igen"
  itable_sub_asl_D2d,
#line 6807 "./mn10300/am33.igen"
  itable_mov_add_D2c,
#line 6826 "./mn10300/am33.igen"
  itable_mov_add_D2d,
#line 6844 "./mn10300/am33.igen"
  itable_mov_sub_D2c,
#line 6863 "./mn10300/am33.igen"
  itable_mov_sub_D2d,
#line 6881 "./mn10300/am33.igen"
  itable_mov_cmp_D2c,
#line 6898 "./mn10300/am33.igen"
  itable_mov_cmp_D2d,
#line 6914 "./mn10300/am33.igen"
  itable_mov_mov_D2c,
#line 6933 "./mn10300/am33.igen"
  itable_mov_mov_D2d,
#line 6951 "./mn10300/am33.igen"
  itable_mov_asr_D2c,
#line 6973 "./mn10300/am33.igen"
  itable_mov_asr_D2d,
#line 6994 "./mn10300/am33.igen"
  itable_mov_lsr_D2c,
#line 7013 "./mn10300/am33.igen"
  itable_mov_lsr_D2d,
#line 7032 "./mn10300/am33.igen"
  itable_mov_asl_D2c,
#line 7051 "./mn10300/am33.igen"
  itable_mov_asl_D2d,
#line 7069 "./mn10300/am33.igen"
  itable_and_add_D2,
#line 7089 "./mn10300/am33.igen"
  itable_and_add_D2b,
#line 7108 "./mn10300/am33.igen"
  itable_and_sub_D2,
#line 7128 "./mn10300/am33.igen"
  itable_and_sub_D2b,
#line 7147 "./mn10300/am33.igen"
  itable_and_cmp_D2,
#line 7165 "./mn10300/am33.igen"
  itable_and_cmp_D2b,
#line 7182 "./mn10300/am33.igen"
  itable_and_mov_D2,
#line 7202 "./mn10300/am33.igen"
  itable_and_mov_D2b,
#line 7221 "./mn10300/am33.igen"
  itable_and_asr_D2,
#line 7244 "./mn10300/am33.igen"
  itable_and_asr_D2b,
#line 7266 "./mn10300/am33.igen"
  itable_and_lsr_D2,
#line 7286 "./mn10300/am33.igen"
  itable_and_lsr_D2b,
#line 7306 "./mn10300/am33.igen"
  itable_and_asl_D2,
#line 7326 "./mn10300/am33.igen"
  itable_and_asl_D2b,
#line 7345 "./mn10300/am33.igen"
  itable_dmach_add_D2,
#line 7370 "./mn10300/am33.igen"
  itable_dmach_add_D2b,
#line 7394 "./mn10300/am33.igen"
  itable_dmach_sub_D2,
#line 7419 "./mn10300/am33.igen"
  itable_dmach_sub_D2b,
#line 7443 "./mn10300/am33.igen"
  itable_dmach_cmp_D2,
#line 7468 "./mn10300/am33.igen"
  itable_dmach_cmp_D2b,
#line 7492 "./mn10300/am33.igen"
  itable_dmach_mov_D2,
#line 7517 "./mn10300/am33.igen"
  itable_dmach_mov_D2b,
#line 7541 "./mn10300/am33.igen"
  itable_dmach_asr_D2,
#line 7568 "./mn10300/am33.igen"
  itable_dmach_asr_D2b,
#line 7594 "./mn10300/am33.igen"
  itable_dmach_lsr_D2,
#line 7619 "./mn10300/am33.igen"
  itable_dmach_lsr_D2b,
#line 7644 "./mn10300/am33.igen"
  itable_dmach_asl_D2,
#line 7669 "./mn10300/am33.igen"
  itable_dmach_asl_D2b,
#line 7693 "./mn10300/am33.igen"
  itable_xor_add_D2,
#line 7713 "./mn10300/am33.igen"
  itable_xor_add_D2b,
#line 7732 "./mn10300/am33.igen"
  itable_xor_sub_D2,
#line 7752 "./mn10300/am33.igen"
  itable_xor_sub_D2b,
#line 7771 "./mn10300/am33.igen"
  itable_xor_cmp_D2,
#line 7789 "./mn10300/am33.igen"
  itable_xor_cmp_D2b,
#line 7806 "./mn10300/am33.igen"
  itable_xor_mov_D2,
#line 7826 "./mn10300/am33.igen"
  itable_xor_mov_D2b,
#line 7845 "./mn10300/am33.igen"
  itable_xor_asr_D2,
#line 7868 "./mn10300/am33.igen"
  itable_xor_asr_D2b,
#line 7890 "./mn10300/am33.igen"
  itable_xor_lsr_D2,
#line 7910 "./mn10300/am33.igen"
  itable_xor_lsr_D2b,
#line 7930 "./mn10300/am33.igen"
  itable_xor_asl_D2,
#line 7950 "./mn10300/am33.igen"
  itable_xor_asl_D2b,
#line 7969 "./mn10300/am33.igen"
  itable_swhw_add_D2,
#line 7989 "./mn10300/am33.igen"
  itable_swhw_add_D2b,
#line 8009 "./mn10300/am33.igen"
  itable_swhw_sub_D2,
#line 8030 "./mn10300/am33.igen"
  itable_swhw_sub_D2b,
#line 8050 "./mn10300/am33.igen"
  itable_swhw_cmp_D2,
#line 8069 "./mn10300/am33.igen"
  itable_swhw_cmp_D2b,
#line 8087 "./mn10300/am33.igen"
  itable_swhw_mov_D2,
#line 8108 "./mn10300/am33.igen"
  itable_swhw_mov_D2b,
#line 8128 "./mn10300/am33.igen"
  itable_swhw_asr_D2,
#line 8152 "./mn10300/am33.igen"
  itable_swhw_asr_D2b,
#line 8175 "./mn10300/am33.igen"
  itable_swhw_lsr_D2,
#line 8196 "./mn10300/am33.igen"
  itable_swhw_lsr_D2b,
#line 8217 "./mn10300/am33.igen"
  itable_swhw_asl_D2,
#line 8238 "./mn10300/am33.igen"
  itable_swhw_asl_D2b,
#line 8258 "./mn10300/am33.igen"
  itable_or_add_D2,
#line 8278 "./mn10300/am33.igen"
  itable_or_add_D2b,
#line 8297 "./mn10300/am33.igen"
  itable_or_sub_D2,
#line 8317 "./mn10300/am33.igen"
  itable_or_sub_D2b,
#line 8336 "./mn10300/am33.igen"
  itable_or_cmp_D2,
#line 8354 "./mn10300/am33.igen"
  itable_or_cmp_D2b,
#line 8371 "./mn10300/am33.igen"
  itable_or_mov_D2,
#line 8391 "./mn10300/am33.igen"
  itable_or_mov_D2b,
#line 8410 "./mn10300/am33.igen"
  itable_or_asr_D2,
#line 8433 "./mn10300/am33.igen"
  itable_or_asr_D2b,
#line 8455 "./mn10300/am33.igen"
  itable_or_lsr_D2,
#line 8475 "./mn10300/am33.igen"
  itable_or_lsr_D2b,
#line 8495 "./mn10300/am33.igen"
  itable_or_asl_D2,
#line 8515 "./mn10300/am33.igen"
  itable_or_asl_D2b,
#line 8534 "./mn10300/am33.igen"
  itable_sat16_add_D2,
#line 8560 "./mn10300/am33.igen"
  itable_sat16_add_D2b,
#line 8585 "./mn10300/am33.igen"
  itable_sat16_sub_D2,
#line 8611 "./mn10300/am33.igen"
  itable_sat16_sub_D2b,
#line 8636 "./mn10300/am33.igen"
  itable_sat16_cmp_D2,
#line 8659 "./mn10300/am33.igen"
  itable_sat16_cmp_D2b,
#line 8681 "./mn10300/am33.igen"
  itable_sat16_mov_D2,
#line 8707 "./mn10300/am33.igen"
  itable_sat16_mov_D2b,
#line 8732 "./mn10300/am33.igen"
  itable_sat16_asr_D2,
#line 8761 "./mn10300/am33.igen"
  itable_sat16_asr_D2b,
#line 8789 "./mn10300/am33.igen"
  itable_sat16_lsr_D2,
#line 8815 "./mn10300/am33.igen"
  itable_sat16_lsr_D2b,
#line 8841 "./mn10300/am33.igen"
  itable_sat16_asl_D2,
#line 8867 "./mn10300/am33.igen"
  itable_sat16_asl_D2b,
#line 8892 "./mn10300/am33.igen"
  itable_mov_llt_D2,
#line 8914 "./mn10300/am33.igen"
  itable_mov_lgt_D2,
#line 8937 "./mn10300/am33.igen"
  itable_mov_lge_D2,
#line 8959 "./mn10300/am33.igen"
  itable_mov_lle_D2,
#line 8982 "./mn10300/am33.igen"
  itable_mov_lcs_D2,
#line 9004 "./mn10300/am33.igen"
  itable_mov_lhi_D2,
#line 9026 "./mn10300/am33.igen"
  itable_mov_lcc_D2,
#line 9048 "./mn10300/am33.igen"
  itable_mov_lls_D2,
#line 9070 "./mn10300/am33.igen"
  itable_mov_leq_D2,
#line 9092 "./mn10300/am33.igen"
  itable_mov_lne_D2,
#line 9114 "./mn10300/am33.igen"
  itable_mov_lra_D2,
#line 4 "./mn10300/am33-2.igen"
  itable_dcpf_D1a,
#line 17 "./mn10300/am33-2.igen"
  itable_dcpf_D1b,
#line 27 "./mn10300/am33-2.igen"
  itable_dcpf_D2a,
#line 42 "./mn10300/am33-2.igen"
  itable_dcpf_D2b,
#line 56 "./mn10300/am33-2.igen"
  itable_dcpf_D4a,
#line 71 "./mn10300/am33-2.igen"
  itable_dcpf_D5a,
#line 88 "./mn10300/am33-2.igen"
  itable_btst_D3,
#line 97 "./mn10300/am33-2.igen"
  itable_bset_D3,
#line 114 "./mn10300/am33-2.igen"
  itable_bclr_D3,
#line 133 "./mn10300/am33-2.igen"
  itable_fmov_D1a,
#line 149 "./mn10300/am33-2.igen"
  itable_fmov_D1b,
#line 166 "./mn10300/am33-2.igen"
  itable_fmov_D1c,
#line 182 "./mn10300/am33-2.igen"
  itable_fmov_D1d,
#line 198 "./mn10300/am33-2.igen"
  itable_fmov_D1e,
#line 214 "./mn10300/am33-2.igen"
  itable_fmov_D1f,
#line 231 "./mn10300/am33-2.igen"
  itable_fmov_D1g,
#line 247 "./mn10300/am33-2.igen"
  itable_fmov_D1h,
#line 263 "./mn10300/am33-2.igen"
  itable_fmov_D1i,
#line 276 "./mn10300/am33-2.igen"
  itable_fmov_D2a,
#line 292 "./mn10300/am33-2.igen"
  itable_fmov_D2b,
#line 309 "./mn10300/am33-2.igen"
  itable_fmov_D2c,
#line 325 "./mn10300/am33-2.igen"
  itable_fmov_D2d,
#line 342 "./mn10300/am33-2.igen"
  itable_fmov_D2e,
#line 358 "./mn10300/am33-2.igen"
  itable_fmov_D2f,
#line 375 "./mn10300/am33-2.igen"
  itable_fmov_D2g,
#line 391 "./mn10300/am33-2.igen"
  itable_fmov_D2h,
#line 408 "./mn10300/am33-2.igen"
  itable_fmov_D4a,
#line 426 "./mn10300/am33-2.igen"
  itable_fmov_D4b,
#line 445 "./mn10300/am33-2.igen"
  itable_fmov_D4c,
#line 462 "./mn10300/am33-2.igen"
  itable_fmov_D4e,
#line 480 "./mn10300/am33-2.igen"
  itable_fmov_D4f,
#line 499 "./mn10300/am33-2.igen"
  itable_fmov_D4g,
#line 517 "./mn10300/am33-2.igen"
  itable_fmov_D5a,
#line 535 "./mn10300/am33-2.igen"
  itable_fmov_D5b,
#line 554 "./mn10300/am33-2.igen"
  itable_fmov_D5c,
#line 572 "./mn10300/am33-2.igen"
  itable_fmov_D5d,
#line 585 "./mn10300/am33-2.igen"
  itable_fmov_D5e,
#line 603 "./mn10300/am33-2.igen"
  itable_fmov_D5f,
#line 622 "./mn10300/am33-2.igen"
  itable_fmov_D5g,
#line 642 "./mn10300/am33-2.igen"
  itable_fmov_D1j,
#line 658 "./mn10300/am33-2.igen"
  itable_fmov_D1k,
#line 675 "./mn10300/am33-2.igen"
  itable_fmov_D1l,
#line 691 "./mn10300/am33-2.igen"
  itable_fmov_D1m,
#line 707 "./mn10300/am33-2.igen"
  itable_fmov_D1n,
#line 724 "./mn10300/am33-2.igen"
  itable_fmov_D1o,
#line 740 "./mn10300/am33-2.igen"
  itable_fmov_D1p,
#line 753 "./mn10300/am33-2.igen"
  itable_fmov_D2i,
#line 770 "./mn10300/am33-2.igen"
  itable_fmov_D2j,
#line 787 "./mn10300/am33-2.igen"
  itable_fmov_D2k,
#line 803 "./mn10300/am33-2.igen"
  itable_fmov_D2l,
#line 820 "./mn10300/am33-2.igen"
  itable_fmov_D2m,
#line 836 "./mn10300/am33-2.igen"
  itable_fmov_D2n,
#line 852 "./mn10300/am33-2.igen"
  itable_fmov_D2o,
#line 869 "./mn10300/am33-2.igen"
  itable_fmov_D2p,
#line 885 "./mn10300/am33-2.igen"
  itable_fmov_D4k,
#line 903 "./mn10300/am33-2.igen"
  itable_fmov_D4l,
#line 922 "./mn10300/am33-2.igen"
  itable_fmov_D4m,
#line 940 "./mn10300/am33-2.igen"
  itable_fmov_D4n,
#line 958 "./mn10300/am33-2.igen"
  itable_fmov_D4o,
#line 977 "./mn10300/am33-2.igen"
  itable_fmov_D4p,
#line 994 "./mn10300/am33-2.igen"
  itable_fmov_D5k,
#line 1012 "./mn10300/am33-2.igen"
  itable_fmov_D5l,
#line 1031 "./mn10300/am33-2.igen"
  itable_fmov_D5m,
#line 1049 "./mn10300/am33-2.igen"
  itable_fmov_D5n,
#line 1067 "./mn10300/am33-2.igen"
  itable_fmov_D5o,
#line 1086 "./mn10300/am33-2.igen"
  itable_fmov_D5p,
#line 1106 "./mn10300/am33-2.igen"
  itable_fmov_D1q,
#line 1124 "./mn10300/am33-2.igen"
  itable_fmov_D1r,
#line 1140 "./mn10300/am33-2.igen"
  itable_fmov_D5,
#line 1159 "./mn10300/am33-2.igen"
  itable_fabs_D1a,
#line 1178 "./mn10300/am33-2.igen"
  itable_fabs_D1b,
#line 1191 "./mn10300/am33-2.igen"
  itable_fabs_D2a,
#line 1210 "./mn10300/am33-2.igen"
  itable_fabs_D2b,
#line 1223 "./mn10300/am33-2.igen"
  itable_fneg_D1a,
#line 1242 "./mn10300/am33-2.igen"
  itable_fneg_D1b,
#line 1255 "./mn10300/am33-2.igen"
  itable_fneg_D2a,
#line 1274 "./mn10300/am33-2.igen"
  itable_fneg_D2b,
#line 1287 "./mn10300/am33-2.igen"
  itable_frsqrt_D1a,
#line 1300 "./mn10300/am33-2.igen"
  itable_frsqrt_D1b,
#line 1313 "./mn10300/am33-2.igen"
  itable_frsqrt_D2a,
#line 1326 "./mn10300/am33-2.igen"
  itable_frsqrt_D2b,
#line 1339 "./mn10300/am33-2.igen"
  itable_fsqrt_D1a,
#line 1352 "./mn10300/am33-2.igen"
  itable_fsqrt_D1b,
#line 1365 "./mn10300/am33-2.igen"
  itable_fsqrt_D2a,
#line 1378 "./mn10300/am33-2.igen"
  itable_fsqrt_D2b,
#line 1391 "./mn10300/am33-2.igen"
  itable_fcmp_D1a,
#line 1404 "./mn10300/am33-2.igen"
  itable_fcmp_D1b,
#line 1417 "./mn10300/am33-2.igen"
  itable_fcmp_D5,
#line 1434 "./mn10300/am33-2.igen"
  itable_fadd_D1a,
#line 1448 "./mn10300/am33-2.igen"
  itable_fadd_D1b,
#line 1461 "./mn10300/am33-2.igen"
  itable_fadd_D2a,
#line 1475 "./mn10300/am33-2.igen"
  itable_fadd_D2b,
#line 1489 "./mn10300/am33-2.igen"
  itable_fadd_D5,
#line 1507 "./mn10300/am33-2.igen"
  itable_fsub_D1a,
#line 1521 "./mn10300/am33-2.igen"
  itable_fsub_D1b,
#line 1534 "./mn10300/am33-2.igen"
  itable_fsub_D2a,
#line 1548 "./mn10300/am33-2.igen"
  itable_fsub_D2b,
#line 1562 "./mn10300/am33-2.igen"
  itable_fsub_D5,
#line 1580 "./mn10300/am33-2.igen"
  itable_fmul_D1a,
#line 1594 "./mn10300/am33-2.igen"
  itable_fmul_D1b,
#line 1607 "./mn10300/am33-2.igen"
  itable_fmul_D2a,
#line 1621 "./mn10300/am33-2.igen"
  itable_fmul_D2b,
#line 1635 "./mn10300/am33-2.igen"
  itable_fmul_D5,
#line 1653 "./mn10300/am33-2.igen"
  itable_fdiv_D1a,
#line 1667 "./mn10300/am33-2.igen"
  itable_fdiv_D1b,
#line 1680 "./mn10300/am33-2.igen"
  itable_fdiv_D2a,
#line 1694 "./mn10300/am33-2.igen"
  itable_fdiv_D2b,
#line 1708 "./mn10300/am33-2.igen"
  itable_fdiv_D5,
#line 1726 "./mn10300/am33-2.igen"
  itable_fmadd_D2,
#line 1741 "./mn10300/am33-2.igen"
  itable_fmsub_D2,
#line 1756 "./mn10300/am33-2.igen"
  itable_fnmadd_D2,
#line 1771 "./mn10300/am33-2.igen"
  itable_fnmsub_D2,
#line 1788 "./mn10300/am33-2.igen"
  itable_ftoi_D2,
#line 1801 "./mn10300/am33-2.igen"
  itable_itof_D2,
#line 1814 "./mn10300/am33-2.igen"
  itable_ftod_D2,
#line 1827 "./mn10300/am33-2.igen"
  itable_dtof_D2,
#line 1842 "./mn10300/am33-2.igen"
  itable_fbeq_D1,
#line 1858 "./mn10300/am33-2.igen"
  itable_fbne_D1,
#line 1874 "./mn10300/am33-2.igen"
  itable_fbgt_D1,
#line 1890 "./mn10300/am33-2.igen"
  itable_fbge_D1,
#line 1906 "./mn10300/am33-2.igen"
  itable_fblt_D1,
#line 1922 "./mn10300/am33-2.igen"
  itable_fble_D1,
#line 1938 "./mn10300/am33-2.igen"
  itable_fbuo_D1,
#line 1954 "./mn10300/am33-2.igen"
  itable_fblg_D1,
#line 1969 "./mn10300/am33-2.igen"
  itable_fbleg_D1,
#line 1985 "./mn10300/am33-2.igen"
  itable_fbug_D1,
#line 2001 "./mn10300/am33-2.igen"
  itable_fbuge_D1,
#line 2017 "./mn10300/am33-2.igen"
  itable_fbul_D1,
#line 2033 "./mn10300/am33-2.igen"
  itable_fbule_D1,
#line 2049 "./mn10300/am33-2.igen"
  itable_fbue_D1,
#line 2065 "./mn10300/am33-2.igen"
  itable_fleq_D0,
#line 2081 "./mn10300/am33-2.igen"
  itable_flne_D0,
#line 2097 "./mn10300/am33-2.igen"
  itable_flgt_D0,
#line 2113 "./mn10300/am33-2.igen"
  itable_flge_D0,
#line 2129 "./mn10300/am33-2.igen"
  itable_fllt_D0,
#line 2145 "./mn10300/am33-2.igen"
  itable_flle_D0,
#line 2161 "./mn10300/am33-2.igen"
  itable_fluo_D0,
#line 2177 "./mn10300/am33-2.igen"
  itable_fllg_D0,
#line 2192 "./mn10300/am33-2.igen"
  itable_flleg_D0,
#line 2208 "./mn10300/am33-2.igen"
  itable_flug_D0,
#line 2224 "./mn10300/am33-2.igen"
  itable_fluge_D0,
#line 2240 "./mn10300/am33-2.igen"
  itable_flul_D0,
#line 2256 "./mn10300/am33-2.igen"
  itable_flule_D0,
#line 2272 "./mn10300/am33-2.igen"
  itable_flue_D0,
  nr_itable_entries,
} itable_index;

typedef enum {
  nr_itable_flags,
} itable_flags;
extern const char * const itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char * const itable_option_names[];

typedef enum {
  itable_processor_am33,
  itable_processor_am33_2,
  itable_processor_mn10300,
  nr_itable_processors,
} itable_processors;
extern const char * const itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  const char *format;
  const char *form;
  const char *flags;
  const char flag[nr_itable_flags + 1];
  const char *options;
  const char option[nr_itable_options + 1];
  const char *processors;
  const char processor[nr_itable_processors + 1];
  const char *name;
  const char *file;
  int line_nr;
} itable_info;

extern const itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 5,
  sizeof_itable_name = 10,
  sizeof_itable_file = 13,
};

#endif /* _ITABLE_H_*/
